/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.sic_rrhh;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import rrhh.Entidad.Empleado;
import rrhh.Entidad.Permisos;
import rrhh.servicio.ServiceHb;

/**
 *
 * @author Matheus
 */
public final class ausentismo extends javax.swing.JPanel {
    Dimension d;
    Empleado emp;
    int turno=1;
    permisos_ausentismo pa = new permisos_ausentismo();
    permisos_permisos pp = new permisos_permisos();
    /**
     * Creates new form inicio
     */
    public ausentismo() {
        initComponents();
        d = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d.width-100, d.height-61);
        setVisible(false);
        agregarpaneles();
        visible(pa);
    }
    
    public void visible(JPanel pane){
        pa.setVisible(false);
        pp.setVisible(false);
        pane.setVisible(true);
    }

    public Dimension getD() {
        return d;
    }

    public void setD(Dimension d) {
        this.d = d;
    }

    public Empleado getEmp() {
        return emp;
    }

    public void setEmp(Empleado emp) {
        this.emp = emp;
    }

    public int getTurno() {
        return turno;
    }

    public void setTurno(int turno) {
        this.turno = turno;
    }

    public permisos_ausentismo getPa() {
        return pa;
    }

    public void setPa(permisos_ausentismo pa) {
        this.pa = pa;
    }

    public permisos_permisos getPp() {
        return pp;
    }

    public void setPp(permisos_permisos pp) {
        this.pp = pp;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }
    
    public void agregarpaneles(){
        pa = new permisos_ausentismo();
        pa.setLocation(0, 61);
        add(pa);
        pp= new permisos_permisos();
        pp.setLocation(0, 61);
        add(pp);
        pp.getjTable1().getColumn("Eliminar").setCellRenderer(new ButtonRenderer());
        pp.getjTable1().addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
            try{
                int row= pp.getjTable1().getSelectedRow();
                int col=pp.getjTable1().getSelectedColumn();
                if(col==6){
                    String selectedSiteName = JOptionPane.showInputDialog(null,"Clave ");
                    if(selectedSiteName.equalsIgnoreCase("cajamarca")){ 
                        try {
                            ServiceHb helper = new ServiceHb();
                            helper.iniciarTransaccion();
                            Permisos h = (Permisos)helper.obtenerObjeto(Permisos.class,(Integer.parseInt(pp.getjTable1().getValueAt(row, col).toString())));
                            helper.eliminarObjeto(h);
                            helper.confirmarTransaccion();
                            helper.cerrarSesion();
                            JOptionPane.showMessageDialog(null,"Hora Extra Eliminada");
                            pp.setTemporal(false);
                            pp.llenar();
                        }catch(Exception io){

                        }
                    }
                }
            }catch(Exception io){

            }
        }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setLayout(null);
        add(jSeparator1);
        jSeparator1.setBounds(10, 60, 1160, 10);

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 74, 152));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ausentismo");
        add(jLabel2);
        jLabel2.setBounds(10, 20, 160, 26);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Permisos");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1);
        jLabel1.setBounds(360, 10, 130, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ausentismo");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3);
        jLabel3.setBounds(220, 10, 120, 40);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
