/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.sic_rrhh;

import Login.ventas.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import rrhh.servicio.Funcion;
import rrhh.servicio.ServiceHb;
import java.awt.Component;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import rrhh.Entidad.Empleado;
import rrhh.Entidad.Evaluacion;


/**
 *
 * @author Angelmath
 */
public final class ingresoevaluacion extends javax.swing.JDialog {
    marco padre;
    Evaluacion evaluacion;
    Empleado empleado;
    /**
     * Creates new form ingresoU
     */
    public ingresoevaluacion(java.awt.Frame parent, marco padre, boolean modal, Evaluacion pf, Empleado emp) {
        super(parent, modal);
        initComponents();
        this.padre=padre;
        this.evaluacion=pf;
        this.empleado=emp;
        setSize(700,580);
        setLocationRelativeTo(null);
        if(evaluacion!=null){
            jTextField1a.setText(evaluacion.getCampo11());
            jTextField2a.setText(evaluacion.getCampo12());
            jTextField3a.setText(evaluacion.getCampo13());
            jTextField4a.setText(evaluacion.getCampo21());
            jTextField5a.setText(evaluacion.getCampo22());
            jTextField6a.setText(evaluacion.getCampo23());
            jTextField7a.setText(evaluacion.getCampo24());
            jTextField8a.setText(evaluacion.getCampo25());
            jTextField9a.setText(evaluacion.getCampo31());
            jTextField10a.setText(evaluacion.getCampo32());
            jTextField11a.setText(evaluacion.getCampo33());
            jTextField12a.setText(evaluacion.getCampo41());
            jTextField13a.setText(evaluacion.getCampo42());
            jTextField14a.setText(evaluacion.getCampo43());
            jTextField15a.setText(evaluacion.getCampo44());
            jTextField16a.setText(evaluacion.getCampo51());
            jTextField17a.setText(evaluacion.getCampo52());
            jTextField18a.setText(evaluacion.getCampo53());
            jTextField19a.setText(evaluacion.getCampo61());
            jTextField20a.setText(evaluacion.getCampo62());
            jTextField21a.setText(evaluacion.getCampo63());
            
            jTextField8.setText(Funcion.DateFormatSql(evaluacion.getFecha()));
            
        }
        Date d = new Date();
        jTextField8.setText(Funcion.DateFormatSql(d));
        jTextField5.setText(emp.getNombre1()+" "+emp.getNombre2()+" "+emp.getApellido1()+" "+emp.getApellido2());

        setVisible(true);
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public marco getPadre() {
        return padre;
    }

    public void setPadre(marco padre) {
        this.padre = padre;
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1a = new javax.swing.JTextField();
        jTextField2a = new javax.swing.JTextField();
        jTextField3a = new javax.swing.JTextField();
        jTextField4a = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5a = new javax.swing.JTextField();
        jTextField6a = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField7a = new javax.swing.JTextField();
        jTextField8a = new javax.swing.JTextField();
        jTextField9a = new javax.swing.JTextField();
        jTextField10a = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11a = new javax.swing.JTextField();
        jTextField12a = new javax.swing.JTextField();
        jTextField13a = new javax.swing.JTextField();
        jTextField16a = new javax.swing.JTextField();
        jTextField17a = new javax.swing.JTextField();
        jTextField18a = new javax.swing.JTextField();
        jTextField14a = new javax.swing.JTextField();
        jTextField15a = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField21a = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField20a = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField19a = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso");
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel11.setText("jLabel8");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(214, 214, 214), new java.awt.Color(214, 214, 214), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 70, 25);
        jLabel11.setVisible(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-salir.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(430, 500, 49, 29);

        jLabel2.setFont(new java.awt.Font("Roboto Light", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingreso de Evaluacion:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 20, 340, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-aceptar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 500, 49, 29);

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 70, 150, 30);

        jTextField5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(210, 70, 270, 30);

        jTextField8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jTextField8.setEnabled(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(210, 100, 270, 30);

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel10.setText("Fecha:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 100, 80, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-eliminar_1_1.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 500, 49, 29);

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel3.setText("VALORES ORGANIZACIONALES.");

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setText("2.- Realiza periódicamente la limpieza de su área de trabajo.");

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setText("3.- Muestra una mejora continua en su desempeño  físico y laboral.");

        jTextField1a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2aActionPerformed(evt);
            }
        });

        jTextField3a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField4a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField4a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel14.setText("4.- No utiliza los equipos de trabajo entregados (computadoras, celulares, etc)");

        jLabel16.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel16.setText("5.- Asiste a las capacitaciones y charlas cuando le  corresponde.");

        jTextField5a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField5a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5aActionPerformed(evt);
            }
        });

        jTextField6a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField6a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel15.setText("1.- Se apega a las normas y procedimientos establecidos.");

        jLabel19.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel19.setText("3.- No requiere de supervision frecuente.");

        jLabel18.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel18.setText("2.- Utiliza de manera adecuada y responsable el equipamiento de seguridad entregado.");

        jTextField7a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField7a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField8a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField8a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8aActionPerformed(evt);
            }
        });

        jTextField9a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField9a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField10a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField10a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel20.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel20.setText("5.- Realiza el trabajo asignado con el esmero y la dedicación requeridos.");

        jLabel17.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel17.setText("4.- Procura estar atento y vigilante durante sus turnos.");

        jLabel21.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel21.setText("2.- Se presenta limpio e impecable al trabajo.");

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel8.setText("1.- Se muestra respetuoso y amable en el trato con los clientes, compañeros y superiores.");

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel7.setText("2.- Brinda una adecuada atención a los clientes.");

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel12.setText("3.- Evita conflictos con sus compañeros de trabajo.");

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel13.setText("1.- Utiliza la indumentaria requerida (Chaleco, gorra,etc).");

        jTextField11a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField11a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField12a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField12a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12aActionPerformed(evt);
            }
        });

        jTextField13a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField13a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField16a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField16a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField17a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField17a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17aActionPerformed(evt);
            }
        });

        jTextField18a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField18a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField14a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField14a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField15a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField15a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel23.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel23.setText("3.- Se presenta al trabajo en forma puntual.");

        jLabel22.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel22.setText("4.- Procura no ausentarse del trabajo.");

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setText("6.- Se muestra profesional en el trabajo.");

        jTextField21a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField21a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel26.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel26.setText("2.- Muestra lealtad a la compañía para la cual trabaja.");

        jLabel25.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel25.setText("3.- Es colaborador y predispuesto.");

        jTextField20a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField20a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20aActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel24.setText("1.- Es honesto y transparente con sus superiores y con la compañía.");

        jTextField19a.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        jTextField19a.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel27.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel27.setText("en asuntos de interés personal.");

        jLabel28.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel28.setText("1.- Realiza las rondas y el patrullaje oportunamente. ");

        jLabel29.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel29.setText("ORIENTACIÓN A RESULTADOS");

        jLabel30.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel30.setText("CALIDAD DE TRABAJO.");

        jLabel31.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel31.setText("RELACIONES INTERPERSONALES.");

        jLabel32.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel32.setText("FORMALIDAD Y BUENA PRESENCIA.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField2a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField3a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField4a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField5a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField6a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField7a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField8a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField9a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField10a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField11a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField12a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField13a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField14a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField15a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField16a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField17a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField18a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField19a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField20a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField21a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel29)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jTextField1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel14)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jTextField4a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField5a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel30)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextField7a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextField8a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jTextField9a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jTextField10a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField11a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel31)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField12a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField13a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField14a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel32)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextField15a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jTextField16a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jTextField17a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jTextField18a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jTextField19a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jTextField20a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jTextField21a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 670, 310);

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 550);

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        dispose(); 
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(validacion()){
        try {
            ServiceHb helper = new ServiceHb();
            helper.iniciarTransaccion();
            if(evaluacion!=null){
                evaluacion.setCampo11(jTextField1a.getText());
                evaluacion.setCampo12(jTextField2a.getText());
                evaluacion.setCampo13(jTextField3a.getText());
                evaluacion.setCampo21(jTextField4a.getText());
                evaluacion.setCampo22(jTextField5a.getText());
                evaluacion.setCampo23(jTextField6a.getText());
                evaluacion.setCampo24(jTextField7a.getText());
                evaluacion.setCampo25(jTextField8a.getText());
                evaluacion.setCampo31(jTextField9a.getText());
                evaluacion.setCampo32(jTextField10a.getText());
                evaluacion.setCampo33(jTextField11a.getText());
                evaluacion.setCampo41(jTextField12a.getText());
                evaluacion.setCampo42(jTextField13a.getText());
                evaluacion.setCampo43(jTextField14a.getText());
                evaluacion.setCampo44(jTextField15a.getText());
                evaluacion.setCampo51(jTextField16a.getText());
                evaluacion.setCampo52(jTextField17a.getText());
                evaluacion.setCampo53(jTextField18a.getText());
                evaluacion.setCampo61(jTextField19a.getText());
                evaluacion.setCampo62(jTextField20a.getText());
                evaluacion.setCampo63(jTextField21a.getText());
                helper.actualizarObjeto(evaluacion);
            }else{
                Evaluacion eva = new Evaluacion();
                eva.setCampo11(jTextField1a.getText());
                eva.setCampo12(jTextField2a.getText());
                eva.setCampo13(jTextField3a.getText());
                eva.setCampo21(jTextField4a.getText());
                eva.setCampo22(jTextField5a.getText());
                eva.setCampo23(jTextField6a.getText());
                eva.setCampo24(jTextField7a.getText());
                eva.setCampo25(jTextField8a.getText());
                eva.setCampo31(jTextField9a.getText());
                eva.setCampo32(jTextField10a.getText());
                eva.setCampo33(jTextField11a.getText());
                eva.setCampo41(jTextField12a.getText());
                eva.setCampo42(jTextField13a.getText());
                eva.setCampo43(jTextField14a.getText());
                eva.setCampo44(jTextField15a.getText());
                eva.setCampo51(jTextField16a.getText());
                eva.setCampo52(jTextField17a.getText());
                eva.setCampo53(jTextField18a.getText());
                eva.setCampo61(jTextField19a.getText());
                eva.setCampo62(jTextField20a.getText());
                eva.setCampo63(jTextField21a.getText());
                Date d1= new Date();
                eva.setFecha(d1);
                eva.setCi(Integer.toString(empleado.getCi()));
                helper.crearOrActualizarObjeto(eva);
            }
            
            helper.confirmarTransaccion();
            helper.cerrarSesion();
           
        } catch (Exception ex) {
            Logger.getLogger(marco.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    
    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JTextField getjTextField1() {
        return jTextField1a;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1a = jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2a;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2a = jTextField2;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getjTextField3() {
        return jTextField3a;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3a = jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField11a;
    }

    public void setjTextField4(JTextField jTextField4) {
        this.jTextField11a = jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public void setjTextField5(JTextField jTextField5) {
        this.jTextField5 = jTextField5;
    }

    public JTextField getjTextField6() {
        return jTextField12a;
    }

    public void setjTextField6(JTextField jTextField6) {
        this.jTextField12a = jTextField6;
    }

    public JTextField getjTextField7() {
        return jTextField13a;
    }

    public void setjTextField7(JTextField jTextField7) {
        this.jTextField13a = jTextField7;
    }

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public void setjTextField8(JTextField jTextField8) {
        this.jTextField8 = jTextField8;
    }

    public boolean validacion(){
        
        if(jTextField1a.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Trote(20min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField2a.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Flexiones de Pecho (1 min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField3a.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Abdominales(1 min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField11a.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Barras (30 seg)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField12a.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Sentadillas (1 min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField13a.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Cabo (30 seg)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        
    return true;
    }
    public void alt (Component bt, String text){
        jLabel11.setVisible(true);
        jLabel11.setText(text);
        jLabel11.setSize((int)jLabel11.getMinimumSize().getWidth(), 25);
        jLabel11.setLocation(bt.getX()+bt.getWidth(), bt.getY()-25);
    }  
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        alt(jButton1,"Aceptar");
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        alt(jButton4,"Salir");
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        alt(jButton2,"Eliminar");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
       jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            ServiceHb helper = new ServiceHb();
            helper.iniciarTransaccion();
            helper.eliminarObjeto(evaluacion);
            helper.confirmarTransaccion();
            helper.cerrarSesion();
        }catch(Exception io){
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public Evaluacion getevaluacion() {
        return evaluacion;
    }

    public void setevaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }

    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public void setjLabel26(JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getjTextField10() {
        return jTextField15a;
    }

    public void setjTextField10(JTextField jTextField10) {
        this.jTextField15a = jTextField10;
    }

    public JTextField getjTextField11() {
        return jTextField4a;
    }

    public void setjTextField11(JTextField jTextField11) {
        this.jTextField4a = jTextField11;
    }

    public JTextField getjTextField12() {
        return jTextField6a;
    }

    public void setjTextField12(JTextField jTextField12) {
        this.jTextField6a = jTextField12;
    }

    public JTextField getjTextField13() {
        return jTextField5a;
    }

    public void setjTextField13(JTextField jTextField13) {
        this.jTextField5a = jTextField13;
    }

    public JTextField getjTextField14() {
        return jTextField9a;
    }

    public void setjTextField14(JTextField jTextField14) {
        this.jTextField9a = jTextField14;
    }

    public JTextField getjTextField15() {
        return jTextField8a;
    }

    public void setjTextField15(JTextField jTextField15) {
        this.jTextField8a = jTextField15;
    }

    public JTextField getjTextField16() {
        return jTextField7a;
    }

    public void setjTextField16(JTextField jTextField16) {
        this.jTextField7a = jTextField16;
    }

    public JTextField getjTextField17() {
        return jTextField10a;
    }

    public void setjTextField17(JTextField jTextField17) {
        this.jTextField10a = jTextField17;
    }

    public JTextField getjTextField18() {
        return jTextField16a;
    }

    public void setjTextField18(JTextField jTextField18) {
        this.jTextField16a = jTextField18;
    }

    public JTextField getjTextField19() {
        return jTextField17a;
    }

    public void setjTextField19(JTextField jTextField19) {
        this.jTextField17a = jTextField19;
    }

    public JTextField getjTextField20() {
        return jTextField18a;
    }

    public void setjTextField20(JTextField jTextField20) {
        this.jTextField18a = jTextField20;
    }

    public JTextField getjTextField21() {
        return jTextField20a;
    }

    public void setjTextField21(JTextField jTextField21) {
        this.jTextField20a = jTextField21;
    }

    public JTextField getjTextField22() {
        return jTextField19a;
    }

    public void setjTextField22(JTextField jTextField22) {
        this.jTextField19a = jTextField22;
    }

    public JTextField getjTextField23() {
        return jTextField21a;
    }

    public void setjTextField23(JTextField jTextField23) {
        this.jTextField21a = jTextField23;
    }

    public JTextField getjTextField9() {
        return jTextField14a;
    }

    public void setjTextField9(JTextField jTextField9) {
        this.jTextField14a = jTextField9;
    }

    private void jTextField2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2aActionPerformed

    private void jTextField12aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12aActionPerformed

    private void jTextField5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5aActionPerformed

    private void jTextField8aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8aActionPerformed

    private void jTextField17aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17aActionPerformed

    private void jTextField20aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20aActionPerformed
    
    public JButton getjButton1() {
        return jButton1;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ingresoevaluacion dialog = new ingresoevaluacion(null,null, true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10a;
    private javax.swing.JTextField jTextField11a;
    private javax.swing.JTextField jTextField12a;
    private javax.swing.JTextField jTextField13a;
    private javax.swing.JTextField jTextField14a;
    private javax.swing.JTextField jTextField15a;
    private javax.swing.JTextField jTextField16a;
    private javax.swing.JTextField jTextField17a;
    private javax.swing.JTextField jTextField18a;
    private javax.swing.JTextField jTextField19a;
    private javax.swing.JTextField jTextField1a;
    private javax.swing.JTextField jTextField20a;
    private javax.swing.JTextField jTextField21a;
    private javax.swing.JTextField jTextField2a;
    private javax.swing.JTextField jTextField3a;
    private javax.swing.JTextField jTextField4a;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField5a;
    private javax.swing.JTextField jTextField6a;
    private javax.swing.JTextField jTextField7a;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField8a;
    private javax.swing.JTextField jTextField9a;
    // End of variables declaration//GEN-END:variables
}
