/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.sic_rrhh;

import Login.ventas.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import rrhh.servicio.Funcion;
import rrhh.servicio.ServiceHb;
import java.awt.Component;
import java.util.Date;
import rrhh.Entidad.Empleado;
import rrhh.Entidad.Pruebasf;

/**
 *
 * @author Angelmath
 */
public final class ingresopruebasf extends javax.swing.JDialog {
    marco padre;
    Pruebasf pruebaf;
    Empleado empleado;
    /**
     * Creates new form ingresoU
     */
    public ingresopruebasf(java.awt.Frame parent, marco padre, boolean modal, Pruebasf pf, Empleado emp) {
        super(parent, modal);
        initComponents();
        this.padre=padre;
        this.pruebaf=pf;
        this.empleado=emp;
        setSize(510,450);
        setLocationRelativeTo(null);
        if(pruebaf!=null){
            jTextField1.setText(pruebaf.getTrote());
            jTextField2.setText(pruebaf.getFlexionesp());
            jTextField3.setText(pruebaf.getAbdominales());
            jTextField4.setText(pruebaf.getBarras());
            jTextField6.setText(pruebaf.getSentadillas());
            jTextField7.setText(pruebaf.getCabo());
            jTextField8.setText(Funcion.DateFormatSql(pruebaf.getFecha()));
            
        }
        Date d = new Date();
        jTextField8.setText(Funcion.DateFormatSql(d));
        jTextField5.setText(emp.getNombre1()+" "+emp.getNombre2()+" "+emp.getApellido1()+" "+emp.getApellido2());

        setVisible(true);
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public marco getPadre() {
        return padre;
    }

    public void setPadre(marco padre) {
        this.padre = padre;
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso");
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel11.setText("jLabel8");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(214, 214, 214), new java.awt.Color(214, 214, 214), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 70, 25);
        jLabel11.setVisible(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-salir.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 370, 49, 29);

        jLabel2.setFont(new java.awt.Font("Roboto Light", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingreso de Prueba Fisica:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 20, 340, 40);

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel3.setText("Trote (20 min):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 110, 30);

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel7.setText("Cabo(30 seg):");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 230, 110, 30);

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel8.setText("Sentadillas(1min):");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 200, 150, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-aceptar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 370, 49, 29);

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 290, 150, 30);

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setText("Barras(30 seg):");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 160, 30);

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setText("Flexiones de Pecho(1min):");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 110, 190, 30);

        jTextField1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 80, 60, 30);

        jTextField2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 110, 60, 30);

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel9.setText("Abdominales(1min):");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 140, 190, 30);

        jTextField3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(280, 140, 60, 30);

        jTextField4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(280, 170, 60, 30);

        jTextField5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(280, 290, 190, 30);

        jTextField6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(280, 200, 60, 30);

        jTextField7.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(280, 230, 60, 30);

        jTextField8.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jTextField8.setEnabled(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(280, 260, 190, 30);

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel10.setText("Fecha:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 260, 80, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-eliminar_1_1.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 370, 49, 29);

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 430);

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        dispose(); 
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(validacion()){
        try {
            ServiceHb helper = new ServiceHb();
            helper.iniciarTransaccion();
            if(pruebaf!=null){
                pruebaf.setTrote(getjTextField1().getText());
                pruebaf.setFlexionesp(getjTextField2().getText());
                pruebaf.setAbdominales(getjTextField3().getText());
                pruebaf.setBarras(getjTextField4().getText());
                pruebaf.setSentadillas(getjTextField6().getText());
                pruebaf.setCabo(getjTextField7().getText());            
                helper.actualizarObjeto(pruebaf);
            }else{
                Pruebasf p = new Pruebasf();
                p.setTrote(getjTextField1().getText());
                p.setFlexionesp(getjTextField2().getText());
                p.setAbdominales(getjTextField3().getText());
                p.setBarras(getjTextField4().getText());
                p.setSentadillas(getjTextField6().getText());
                p.setCabo(getjTextField7().getText());     
                Date d1= new Date();
                p.setFecha(d1);
                p.setCi(""+(empleado.getCi()));
                helper.crearOrActualizarObjeto(p);
            }
            
            helper.confirmarTransaccion();
            helper.cerrarSesion();
           
        } catch (Exception ex) {
            Logger.getLogger(marco.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    
    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public void setjTextField4(JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public void setjTextField5(JTextField jTextField5) {
        this.jTextField5 = jTextField5;
    }

    public JTextField getjTextField6() {
        return jTextField6;
    }

    public void setjTextField6(JTextField jTextField6) {
        this.jTextField6 = jTextField6;
    }

    public JTextField getjTextField7() {
        return jTextField7;
    }

    public void setjTextField7(JTextField jTextField7) {
        this.jTextField7 = jTextField7;
    }

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public void setjTextField8(JTextField jTextField8) {
        this.jTextField8 = jTextField8;
    }

    public boolean validacion(){
        
        if(jTextField1.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Trote(20min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField2.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Flexiones de Pecho (1 min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField3.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Abdominales(1 min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField4.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Barras (30 seg)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField6.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Sentadillas (1 min)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        if(jTextField7.getText().equalsIgnoreCase("")){
            JOptionPane.showConfirmDialog(null, "Falta Campo de Cabo (30 seg)", "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
            return false;
        }
        
    return true;
    }
    public void alt (Component bt, String text){
        jLabel11.setVisible(true);
        jLabel11.setText(text);
        jLabel11.setSize((int)jLabel11.getMinimumSize().getWidth(), 25);
        jLabel11.setLocation(bt.getX()+bt.getWidth(), bt.getY()-25);
    }  
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        alt(jButton1,"Aceptar");
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        alt(jButton4,"Salir");
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        alt(jButton2,"Eliminar");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
       jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            ServiceHb helper = new ServiceHb();
            helper.iniciarTransaccion();
            helper.eliminarObjeto(pruebaf);
            helper.confirmarTransaccion();
            helper.cerrarSesion();
        }catch(Exception io){
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public JButton getjButton1() {
        return jButton1;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresoU3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ingresopruebasf dialog = new ingresopruebasf(null,null, true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
