/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.sic_rrhh;

import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import rrhh.Entidad.Departamento;
import rrhh.sic_rrhh.lista_departamentos.ausen;

/**
 *
 * @author Angelmath
 */
public final class ingresoU21 extends javax.swing.JDialog {
    Departamento marc;
    /**
     * Creates new form ingresoU
     */
    public ingresoU21(java.awt.Frame parent, boolean modal,ArrayList<ausen> dou,int dias, int empleados, String depa) {
        super(parent, modal);
        initComponents();
        setSize(880,360);
        dispose();
        setUndecorated(true);
        setLocationRelativeTo(null);
        jLabel3.setText(depa);
        this.marc=marc;
        DefaultTableModel temp4 = (DefaultTableModel) jTable1.getModel();
        for(int i=temp4.getRowCount()-1;i>=0;i--){
           temp4.removeRow(i);
        }
        DecimalFormat formateador = new DecimalFormat("####.####");
        for(int i=0; i<dou.size();i++){
            if(jTable1.getRowCount()< dou.size()){
                DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
                Object nuevo[]= {temp.getRowCount()+1,"",""};
                temp.addRow(nuevo);
            }
            jTable1.getModel().setValueAt(dou.get(i).getFecha(), i, 0);
            jTable1.getModel().setValueAt(dou.get(i).getFc1(), i, 1);
            jTable1.getModel().setValueAt("%" +formateador.format ((((dou.get(i).getFc()/60)/12)/dias)/empleados), i, 2);
            jTable1.getModel().setValueAt(dou.get(i).getFs1(), i, 3);
            jTable1.getModel().setValueAt("%" +formateador.format ((((dou.get(i).getFs()/60)/12)/dias)/empleados), i, 4);
            jTable1.getModel().setValueAt(dou.get(i).getFf1(), i, 5);
            jTable1.getModel().setValueAt("%" +formateador.format ((((dou.get(i).getFf()/60)/12)/dias)/empleados), i, 6);
            jTable1.getModel().setValueAt(dou.get(i).getA1(), i, 7);
            jTable1.getModel().setValueAt("%" +formateador.format ((((dou.get(i).getA()/60)/12)/dias)/empleados), i, 8);
            jTable1.getModel().setValueAt(dou.get(i).getAs1(), i, 9);
            jTable1.getModel().setValueAt("%" +formateador.format ((((dou.get(i).getAs()/60)/12)/dias)/empleados), i, 10);
            jTable1.getModel().setValueAt(dou.get(i).getP1(), i, 11);
            jTable1.getModel().setValueAt("%" +formateador.format ((((dou.get(i).getP()/60)/12)/dias)/empleados), i, 12);
            jTable1.getModel().setValueAt("%" +formateador.format (((((dou.get(i).getFc()+dou.get(i).getFs()+dou.get(i).getFf()+dou.get(i).getA()+dou.get(i).getAs()+dou.get(i).getP())/60)/12)/dias)/empleados), i, 13);
        }
        setVisible(true);
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }
    
    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }
    
    public void alt (Component bt, String text){
        jLabel9.setVisible(true);
        jLabel9.setText(text);
        jLabel9.setSize((int)jLabel9.getMinimumSize().getWidth(), 25);
        jLabel9.setLocation(bt.getX()+bt.getWidth(), bt.getY()-25);
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso");
        setMinimumSize(new java.awt.Dimension(378, 320));
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "N°", "F. Inj. - Av. con T.", "N°", "F. Inj. - Av. sin T.", "N°", "F. Inj. - No Avisó", "N°", "Atraso - Avisó", "N°", "Atraso - No Avisó", "N°", "Permisos", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(28);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(1).setMinWidth(40);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(3).setMinWidth(40);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(5).setMinWidth(40);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(7).setMinWidth(40);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(9).setMinWidth(40);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(11).setMinWidth(40);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(11).setMaxWidth(40);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 810, 230);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel9.setText("jLabel8");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(214, 214, 214), new java.awt.Color(214, 214, 214), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 70, 25);
        jLabel9.setVisible(false);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 20, 190, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-salir.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 310, 49, 29);

        jLabel2.setFont(new java.awt.Font("Roboto Light", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tabla de Ausentismo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 330, 30);

        jLabel1.setBackground(new java.awt.Color(242, 242, 242));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, -2, 880, 360);

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        dispose(); 
    }//GEN-LAST:event_jButton4MouseClicked


 public void empleados(){    
    
    
    }
    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        alt(jButton4,"Salir");
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresoU21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresoU21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresoU21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresoU21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ingresoU21 dialog = new ingresoU21(new javax.swing.JFrame(), true, null,0,0,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
