/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.sic_rrhh;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import rrhh.Entidad.Empleado;

/**
 *
 * @author Matheus
 */
public class perfil_empleado extends javax.swing.JPanel {
    Dimension d;
    Empleado emp;
    
    int turno=1;
    /**
     * Creates new form inicio
     */
    public perfil_empleado() {
        initComponents();
        
        d = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d.width-100, d.height-61);
        setVisible(false);
        jSeparator1.setSize(d.width-180, 3);
    }

    public Dimension getD() {
        return d;
    }

    public void setD(Dimension d) {
        this.d = d;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public void setjLabel26(JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }

    public JLabel getjLabel27() {
        return jLabel27;
    }

    public void setjLabel27(JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    public JLabel getjLabel28() {
        return jLabel28;
    }

    public void setjLabel28(JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public Empleado getEmp() {
        return emp;
    }

    public void setEmp(Empleado emp) {
        this.emp = emp;
    }

    public int getTurno() {
        return turno;
    }

    public void setTurno(int turno) {
        this.turno = turno;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSeparator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JSeparator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setLayout(null);
        add(jSeparator1);
        jSeparator1.setBounds(30, 90, 980, 10);

        jLabel7.setBackground(new java.awt.Color(0, 0, 255));
        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);
        add(jLabel7);
        jLabel7.setBounds(160, 160, 30, 30);
        jLabel7.setVisible(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/accounts-icon-lightblue.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentHidden(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(30, 50, 30, 30);

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 74, 152));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Perfil de Empleado");
        add(jLabel2);
        jLabel2.setBounds(90, 50, 300, 26);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3);
        jSeparator3.setBounds(70, 50, 10, 20);

        jLabel4.setBackground(new java.awt.Color(230, 230, 230));
        jLabel4.setOpaque(true);
        add(jLabel4);
        jLabel4.setBounds(50, 110, 70, 80);

        jLabel5.setFont(new java.awt.Font("Roboto", 3, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 74, 151));
        jLabel5.setText("Nombre de Empleado");
        add(jLabel5);
        jLabel5.setBounds(160, 110, 390, 30);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 173, 218));
        jLabel6.setText("Cargo");
        add(jLabel6);
        jLabel6.setBounds(160, 140, 350, 20);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-IG-darkblue.png"))); // NOI18N
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        add(jLabel25);
        jLabel25.setBounds(490, 50, 31, 31);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HL-lightblue.png"))); // NOI18N
        jLabel26.setOpaque(true);
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });
        add(jLabel26);
        jLabel26.setBounds(540, 50, 31, 31);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-D-lightblue.png"))); // NOI18N
        jLabel27.setOpaque(true);
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });
        add(jLabel27);
        jLabel27.setBounds(590, 50, 31, 31);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HM-lightblue.png"))); // NOI18N
        jLabel28.setOpaque(true);
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });
        add(jLabel28);
        jLabel28.setBounds(640, 50, 31, 31);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setEnabled(false);
        jLabel11.setOpaque(true);
        add(jLabel11);
        jLabel11.setBounds(0, 0, 70, 25);
        jLabel11.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-IG-darkblue.png"))); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HL-lightblue.png"))); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-D-lightblue.png"))); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HM-lightblue.png"))); // NOI18N
        turno=1;
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
       if(turno!=1){
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-IG-darkblue.png"))); // NOI18N
       }
       alt(jLabel25,"Informacion General");
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        if(turno!=1){
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-IG-lightblue.png"))); // NOI18N
        }
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-IG-lightblue.png"))); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HL-darkblue.png"))); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-D-lightblue.png"))); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HM-lightblue.png"))); // NOI18N
        turno=3;
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-IG-lightblue.png"))); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HL-lightblue.png"))); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-D-darkblue.png"))); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HM-lightblue.png"))); // NOI18N
        turno=4;
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        if(turno!=3){
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HL-darkblue.png"))); // NOI18N
        }
        alt(jLabel26,"Historia Laboral");
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
        jLabel11.setVisible(false);
        if(turno!=3){
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HL-lightblue.png"))); // NOI18N
        }
    }//GEN-LAST:event_jLabel26MouseExited

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        if(turno!=4){
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-D-darkblue.png"))); // NOI18N
        }
        alt(jLabel27,"Desempeño");
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        jLabel11.setVisible(false);
        if(turno!=4){
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-D-lightblue.png"))); // NOI18N
        }
    }//GEN-LAST:event_jLabel27MouseExited

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-IG-lightblue.png"))); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HL-lightblue.png"))); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-D-lightblue.png"))); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HM-darkblue.png"))); // NOI18N
        turno=5;
    }//GEN-LAST:event_jLabel28MouseClicked
public void alt (Component bt, String text){
        jLabel11.setVisible(true);
        jLabel11.setText(text);
        jLabel11.setSize((int)jLabel11.getMinimumSize().getWidth(), 25);
        jLabel11.setLocation(bt.getX()+bt.getWidth(), bt.getY()-25);
    }  
    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        if(turno!=5){
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HM-darkblue.png"))); // NOI18N
        }
        alt(jLabel28,"Historial Medico");
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        jLabel11.setVisible(false);
        if(turno!=5){
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/boton-HM-lightblue.png"))); // NOI18N
        }
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
       alt(jLabel1,"Editar Empleado");
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
       jLabel11.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentHidden

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
