/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.sic_rrhh;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Matheus
 */
public class perfil_empleado_pruebasfisicas extends javax.swing.JPanel {
    Dimension d;
    
    /**
     * Creates new form inicio
     */
    public perfil_empleado_pruebasfisicas() {
        initComponents();
        d = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d.width-100, d.height-61-200);
        jScrollPane1.setSize(d.width-102, d.height-61-200);
        jPanel1.setSize(d.width-102, d.height-61-200);
        String ex ="";
        
        setVisible(false);
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public Dimension getD() {
        return d;
    }

    public void setD(Dimension d) {
        this.d = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setLayout(null);

        jLabel7.setBackground(new java.awt.Color(230, 230, 230));
        jLabel7.setFont(new java.awt.Font("Roboto", 3, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 74, 151));
        jLabel7.setText("PRUEBAS FISICAS");
        jLabel7.setOpaque(true);
        add(jLabel7);
        jLabel7.setBounds(0, 0, 250, 30);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
        jScrollPane1.setBounds(410, 0, 710, 600);

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setText("Esfuerzo Anaerobico");
        add(jLabel1);
        jLabel1.setBounds(10, 130, 170, 40);

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel2.setText("Esfuerzo Aerobico");
        add(jLabel2);
        jLabel2.setBounds(10, 60, 170, 40);

        jLabel4.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel4.setText("Trote (20 min)");
        add(jLabel4);
        jLabel4.setBounds(140, 100, 230, 30);

        jLabel6.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel6.setText("Flexiones de Pecho (1 min)");
        add(jLabel6);
        jLabel6.setBounds(140, 170, 230, 30);

        jLabel8.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel8.setText("Abdominales(1 min)");
        add(jLabel8);
        jLabel8.setBounds(140, 210, 230, 30);

        jLabel9.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel9.setText("Barras (30 seg)");
        add(jLabel9);
        jLabel9.setBounds(140, 250, 230, 30);

        jLabel10.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel10.setText("Sentadillas (1 min)");
        add(jLabel10);
        jLabel10.setBounds(140, 290, 230, 30);

        jLabel11.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel11.setText("Cabo (30 seg)");
        add(jLabel11);
        jLabel11.setBounds(140, 330, 230, 30);

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel15.setText("Eliminar");
        add(jLabel15);
        jLabel15.setBounds(10, 370, 120, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrhh/imagenes/agregar-icon-blue.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel5);
        jLabel5.setBounds(260, 0, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
