/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rrhh.sic_rrhh;

import java.awt.Dimension;
import java.awt.Toolkit;
import rrhh.Entidad.Empleado;

/**
 *
 * @author Matheus
 */
public final class reportes_estadistico extends javax.swing.JPanel {
    Dimension d;
    Empleado emp;
    int turno=1;
    /**
     * Creates new form inicio
     */
    public reportes_estadistico() {
        initComponents();
        d = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d.width-100, d.height-61);
        jPanel1.setLocation((d.width-100)/2 - jPanel1.getWidth()/2,0);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 70, 1160, 10);

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 74, 152));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reportes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 160, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/enconstruccion.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 150, 260, 270);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1210, 630);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
