package Bitacora.tablas;
// Generated 23/03/2015 16:39:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Registros generated by hbm2java
 */
public class Registros  implements java.io.Serializable {


     private int id;
     private Monitor monitor;
     private Usuario usuario;
     private Character tipoIngreso;
     private String observacion;
     private Date fechaIngreso;
     private Date fechaSalida;
     private String localidad;

    public Registros() {
    }

	
    public Registros(int id) {
        this.id = id;
    }
    public Registros(int id, Monitor monitor, Usuario usuario, Character tipoIngreso, String observacion, Date fechaIngreso, Date fechaSalida, String localidad) {
       this.id = id;
       this.monitor = monitor;
       this.usuario = usuario;
       this.tipoIngreso = tipoIngreso;
       this.observacion = observacion;
       this.fechaIngreso = fechaIngreso;
       this.fechaSalida = fechaSalida;
       this.localidad = localidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Monitor getMonitor() {
        return this.monitor;
    }
    
    public void setMonitor(Monitor monitor) {
        this.monitor = monitor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Character getTipoIngreso() {
        return this.tipoIngreso;
    }
    
    public void setTipoIngreso(Character tipoIngreso) {
        this.tipoIngreso = tipoIngreso;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }




}


