/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Login.ventas;

import Login.Entidad.Caldepartamento;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author Matheus
 */
public class calendariofiltro3 extends javax.swing.JPanel {
    ArrayList<Component> list = new ArrayList<Component>();
    List<Caldepartamento> lista2;
    /**
     * Creates new form calendariofiltro1
     */
    public calendariofiltro3(List<Caldepartamento> listdepa ) {
        initComponents();
        setLayout(null);
        lista2=listdepa;
        int posx=0;
        int posy=0;
        final ImageIcon icon2= new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/calendario-menu-grey-2.png"));
        JLabel lm = new JLabel(){
        @Override
        public void paintComponent(Graphics g) {
          g.drawImage(icon2.getImage(), 0, 0, null);
          super.paintComponent(g);
        }
      };
        lm.setFont(new java.awt.Font("Roboto", 1, 11));
        lm.setText("  Filtros");
        lm.setForeground(new java.awt.Color(0, 173, 238));
        lm.setVisible(true);
        lm.setOpaque(false);
        lm.setBounds(posx, posy, 160, 35);
        add(lm);
        posy= posy+35;
        for (Caldepartamento lista21 : lista2) {
            final JCheckBox l = new JCheckBox();
            l.setText(lista21.getNombre());
            String[] temp = lista21.getColor().split(",");
            l.setFont(new java.awt.Font("Roboto", 0, 9));
            l.setForeground(new java.awt.Color(Integer.parseInt(temp[0]), Integer.parseInt(temp[1]), Integer.parseInt(temp[2])));
            l.setBackground(new Color(247,247,247));
            l.setSelected(true);
            l.setOpaque(true);
            l.setBorderPainted(true);
            l.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 227, 227)));
            l.setBounds(posx, posy, 160, 30);
            l.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    
                }
                @Override
                public void mouseExited(MouseEvent e) {
                    
                }
                @Override
                public void mouseClicked(MouseEvent e) {
                    
                }
            });
            l.setVisible(false);
            add(l);
            list.add(l);
            posy= posy+30;
        }
         
        lm.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    
                }
                @Override
                public void mouseClicked(MouseEvent e) {
                    for(Component i: list){
                        i.setVisible(!i.isVisible());
                    }
                }
        });
        setSize(160,395);
        setPreferredSize(new Dimension(160,395));
        setVisible(true);
    }

    public ArrayList<Component> getList() {
        return list;
    }

    public void setList(ArrayList<Component> list) {
        this.list = list;
    }
    
    public void setLista2(ArrayList<Caldepartamento> lista2) {
        this.lista2 = lista2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
