/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Login.ventas;

import Login.Entidad.Clientes;
import Login.Entidad.Ctecobrar;
import Login.Entidad.Factu;
import Login.Entidad.Instalacion;
import Login.Entidad.Proyectos;
import Login.Entidad.Report;
import Login.Entidad.Retencionfactu;
import Login.Entidad.Ticket;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import Login.servicio.ServiceHb;
import static Login.ventas.marco.reiniciarJTable;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelmath
 */
public final class editarfacturas extends javax.swing.JDialog {
    marco padre;
    instalacion empl;
    String cl;
    int toca;
    int idnuevo;
    Ticket tk;
    Instalacion instalacion;
    Proyectos py;
    Clientes clientes;
    int cobrar;
    String idpy;
    List<Ctecobrar> ltcc=null;
    DecimalFormat df = new DecimalFormat("0.00");
    /**
     * Creates new form ingresoU
     * @param parent
     * @param padre
     * @param modal
     * @param ct
     */
    public editarfacturas(java.awt.Frame parent, marco padre, boolean modal, int ct) {
        super(parent,modal);
        initComponents();
        List<Report> list4 = null;
        List<Factu> fac =null;
        this.padre=padre;
        this.cobrar=ct;
        setSize(1025,245);
        Calendar ca = Calendar.getInstance();
        jTable1.getColumn("Editar").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Eliminar").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Ver Ret.").setCellRenderer(new ButtonRenderer());
        setLocationRelativeTo(null);
        llenar();
        setVisible(true);
    }
    public void llenar(){
        try {
            ServiceHb helper = new ServiceHb();
            helper.iniciarTransaccion();
            ltcc = helper.getListCteCobrar(cobrar);
            helper.cerrarSesion();        
        } catch (Exception io) {
        }
        reiniciarJTable(jTable1);
        if(ltcc!=null){
            for(Ctecobrar i: ltcc){
                float sub = 0;
                float iva = 0;
                float val = 0;
                float val2 = 0;
                float rett = 0;
                if(i.getSubmontos()!=null){
                    sub = Float.parseFloat(i.getSubmontos());
                }
                if(i.getIvamontos()!=null){
                    iva = Float.parseFloat(i.getIvamontos());
                }
                if(i.getMontos()!=null){
                    val = Float.parseFloat(i.getMontos());
                }
                if(i.getSaldo()!=null){
                    val2 = Float.parseFloat(i.getSaldo());
                }   
                if(i.getTotalretencion()!=null){
                    rett = Float.parseFloat(i.getTotalretencion());
                }
                float totalfact= val-rett;
                DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
                Object nuevo[]= {i.getId(),i.getFecha(),i.getFactura(),i.getCliente(),i.getAutfactura(),i.getPlanpagos(),i.getObservacion(),"$"+df.format(sub).replace(",", "."),"$"+df.format(iva).replace(",", "."),"$"+df.format(val).replace(",", "."),"$"+df.format(rett).replace(",", "."),i.getNumretencion(),i.getIdretencion(),"$"+df.format(totalfact).replace(",", "."),"$"+df.format(val2).replace(",", "."),"$"+df.format(val-val2-rett).replace(",", "."),i,i};
                temp.addRow(nuevo);
            }
        }
    }
    public Ticket getTk() {
        return tk;
    }
    
    public void setTk(Ticket tk) {
        this.tk = tk;
    }
   
    public marco getPadre() {
        return padre;
    }
    
    public void setPadre(marco padre) {
        this.padre = padre;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso");
        setMinimumSize(new java.awt.Dimension(500, 245));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel11.setText("jLabel8");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(214, 214, 214), new java.awt.Color(214, 214, 214), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 70, 25);
        jLabel11.setVisible(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/boton-salir.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(460, 180, 49, 29);

        jLabel2.setFont(new java.awt.Font("Roboto Light", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Instalacion");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 20, 340, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "N° Factura", "Cliente", "Aut. Factura", "Pagos", "Observacion", "SubTotal", "Iva", "Total", "Retencion T.", "N° Ret.", "Ver Ret.", "Total Factura", "Pagado", "Saldos", "Editar", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(35);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(5).setMinWidth(200);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(6).setMinWidth(200);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 976, 90);

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        dispose(); 
    }//GEN-LAST:event_jButton4MouseClicked
    
    public void alt (Component bt, String text){
        
    }   
    
    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        alt(jButton4,"Salir");
    }//GEN-LAST:event_jButton4MouseEntered
                
    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton4MouseExited
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        if(col==12){
            String fnum = jTable1.getValueAt(row, 2).toString();
            String idret = jTable1.getValueAt(row, 12).toString();
            String idctecobrar = jTable1.getValueAt(row, 0).toString();
            Double d = Double.parseDouble(jTable1.getValueAt(row, 7).toString().replace("$",""));
            Retencionfactu retencion=null;
            try{
                ServiceHb helper = new ServiceHb();
                helper.iniciarTransaccion();
                if(!idret.equalsIgnoreCase("")){
                    retencion=helper.getrentencion(idret);
                }
                helper.cerrarSesion();
            }catch(Exception io){}
            
            if(retencion!=null){
                retencionctecobrar retencion1 = new retencionctecobrar(null, null, true,retencion,idctecobrar,d);
            }else{
                retencionctecobrar retencion1 = new retencionctecobrar(null, null, true,null,idctecobrar,d);
            }
            llenar();
        }
        if(col==16){
            try{
                ServiceHb helper = new ServiceHb();
                helper.iniciarTransaccion();
                Ctecobrar ce = (Ctecobrar)helper.obtenerObjeto(Ctecobrar.class, Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
                ce.setFactura(jTable1.getValueAt(row, 2).toString());
                ce.setCliente(jTable1.getValueAt(row, 3).toString());
                ce.setAutfactura(jTable1.getValueAt(row, 4).toString());
                ce.setPlanpagos(jTable1.getValueAt(row, 5).toString());
                ce.setObservacion(jTable1.getValueAt(row, 6).toString());
                ce.setSubmontos(jTable1.getValueAt(row, 7).toString().replace("$","").replace(",","."));
                ce.setIvamontos(jTable1.getValueAt(row, 8).toString().replace("$","").replace(",","."));
                ce.setMontos(jTable1.getValueAt(row, 9).toString().replace("$","").replace(",","."));
                ce.setSaldo(jTable1.getValueAt(row, 14).toString().replace("$","").replace(",","."));
                ce.setTotalretencion(jTable1.getValueAt(row, 10).toString().replace("$","").replace(",","."));
                ce.setNumretencion(jTable1.getValueAt(row, 11).toString());
                
                String[] cadena = jTable1.getValueAt(row, 1).toString().split("-");
                Calendar ca = Calendar.getInstance();
                ca.set(Integer.parseInt(cadena[0]), Integer.parseInt(cadena[1])-1, Integer.parseInt(cadena[2]));
                ce.setFecha( new java.sql.Date(ca.getTime().getTime()));
                
                helper.actualizarObjeto(ce);
                helper.confirmarTransaccion();
                helper.cerrarSesion();
                JOptionPane.showMessageDialog(null, "Editado");
            }catch(Exception io){}
            dispose();
        }
        if(col==17){
            try{
                ServiceHb helper = new ServiceHb();
                helper.iniciarTransaccion();
                Ctecobrar ce = (Ctecobrar)jTable1.getValueAt(row, 16);
                helper.eliminarObjeto(ce);
                helper.confirmarTransaccion();
                helper.cerrarSesion();
                JOptionPane.showMessageDialog(null, "Editado");
            }catch(Exception io){}
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        if((evt.getKeyChar()=="p".charAt(0))){
            
        }
        if((evt.getKeyChar()=="o".charAt(0))){
            
        }
    }//GEN-LAST:event_jTable1KeyTyped
    
    public instalacion getEmpl() {
        return empl;
    }
    
    public void setEmpl(instalacion empl) {
        this.empl = empl;
    }
    
    public String getCl() {
        return cl;
    }
    
    public void setCl(String cl) {
        this.cl = cl;
    }
    
    public int getToca() {
        return toca;
    }
    
    public JTextField getjTextField5() {
        return null;
    }
    
    public void setjTextField5(JTextField jTextField5) {
        //this.jTextField5 = jTextField5;
    }
    
    public void setToca(int toca) {
        this.toca = toca;
    }
 
    public JButton getjButton4() {
        return jButton4;
    }
    
    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }
    
    public JLabel getjLabel2() {
        return jLabel2;
    }
    
    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarfacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

