/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Login.ventas;

import Login.Entidad.Instalacion;
import Login.Entidad.Login;
import Login.servicio.ServiceHb;
import static Login.ventas.marco.reiniciarJTable;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author homemig
 */
public final class pylsoporte2 extends javax.swing.JPanel {
    Login us;
    int breakhilo=0;
    int idcliente=0;
    int idinstalacion=0;
    String nombrecliente="";
    String nombreinstalacion="";
    /**
     * Creates new form inventario
     */
    public pylsoporte2() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        setVisible(false);
        setSize(d.width, d.height-95);
        jPanel3.setLocation((d.width/2)-(jPanel3.getWidth()/2), jPanel3.getY());
        jScrollPane2.setSize(d.width-70, (d.height-300));
        jScrollPane2.setLocation((d.width/2)-(jScrollPane2.getWidth()/2), jPanel3.getHeight()+jPanel3.getY());
    }

    public Login getUs() {
        return us;
    }

    public void setUs(Login us) {
        this.us = us;
    }

    public int getBreakhilo() {
        return breakhilo;
    }

    public void setBreakhilo(int breakhilo) {
        this.breakhilo = breakhilo;
    }

    public int getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    public int getIdinstalacion() {
        return idinstalacion;
    }

    public void setIdinstalacion(int idinstalacion) {
        this.idinstalacion = idinstalacion;
    }

    public String getNombrecliente() {
        return nombrecliente;
    }

    public void setNombrecliente(String nombrecliente) {
        this.nombrecliente = nombrecliente;
    }

    public String getNombreinstalacion() {
        return nombreinstalacion;
    }

    public void setNombreinstalacion(String nombreinstalacion) {
        this.nombreinstalacion = nombreinstalacion;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jTextField2.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(100, 10, 210, 30);

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Buscar:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 17, 60, 14);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/icono-buscar.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        jPanel3.add(jLabel7);
        jLabel7.setBounds(310, 10, 30, 30);

        add(jPanel3);
        jPanel3.setBounds(370, 10, 350, 50);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Detalle Breve", "Fecha", "Estado", "Tipo", "Accion", "Eliminar", "Editar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(24);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setMinWidth(100);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(50, 60, 890, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        hilollenarcerotexto();
    }//GEN-LAST:event_jTextField2KeyTyped
    
    public void hilollenarcero(){
        updateTablas up = new updateTablas(3);
        up.start();
    }
    
    public void hilollenarcerotexto(){
        updateTablas up = new updateTablas(4);
        up.start();
    }
    
     public class updateTablas extends Thread {
        int turno;
        public updateTablas(int turno){
            this.turno=turno;
        }
        
        @Override
        public void run() {
            breakhilo=1;
            try{
                sleep(800);
                breakhilo=0;
            }catch(Exception io){
            }
            
            if(turno==1){
                //llenar();
            }
            if(turno==2){
                //llenarcero();
            }
            if(turno==3){
                llenarsoporte();
            }
            if(turno==4){
                llenarsoportetexto();
            }
            
        }
    }
     
    public void llenarsoportetexto(){
        try{
            ServiceHb helper = new ServiceHb();
            helper.iniciarTransaccion();
            List<Instalacion> list = helper.getlistaInstalacionSoporteBodega(jTextField2.getText());
            helper.cerrarSesion();
            reiniciarJTable(jTable2);
            if(list!=null){
                DefaultTableModel temp = (DefaultTableModel) jTable2.getModel();
                for(Instalacion x: list){
                    if(breakhilo==1){
                        break;
                    }
                    String c= x.getClientes().getApellido();
                    String c1=x.getDetalle();
                    String c2=formatoFecha(x.getFecha());
                    String c3=x.getProceso();
                    String c4=x.getTipo();
                    String c5=""+x.getId();
                    String c6=""+x.getId();
                    String c7=""+x.getId();
                    Object nuevo[]= {c,c1,c2,c3,c4,c5,c6,c7};
                    temp.addRow(nuevo);
                }

            }
        }catch(Exception io){

        }
    } 
     
    public void llenarsoporte(){
            try{
                ServiceHb helper = new ServiceHb();
                helper.iniciarTransaccion();
                List<Instalacion> list = helper.getlistaInstalacionSoporteBodega();
                reiniciarJTable(jTable2);
                if(list!=null){
                    DefaultTableModel temp = (DefaultTableModel) jTable2.getModel();
                    for(Instalacion x: list){
                        if(breakhilo==1){
                            break;
                        }
                        String c= x.getClientes().getApellido();
                        String c1=x.getDetalle();
                        String c2=formatoFecha(x.getFecha());
                        String c3=x.getProceso();
                        String c4=x.getTipo();
                        String c5=""+x.getId();
                        String c6=""+x.getId();
                        String c7=""+x.getId();
                        Object nuevo[]= {c,c1,c2,c3,c4,c5,c6,c7};
                        temp.addRow(nuevo);
                    }
                }
                helper.cerrarSesion();
        }catch(Exception io){
        }
    } 
    
    public String formatoFecha(String fecha){
        String cadena[]= fecha.split("/");
        if(fecha.contains("/")){
            return cadena[2]+"-"+cadena[1]+"-"+cadena[0];
        }
        return fecha;
        
    }
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();
        int col = jTable2.getSelectedColumn();
        if(col==5){
            idinstalacion= Integer.parseInt(jTable2.getValueAt(row, col).toString());
            nombreinstalacion=jTable2.getValueAt(row, 0).toString();
            pylproformassoporte ppf= new pylproformassoporte(null, null, true, ""+idcliente,nombrecliente,""+idinstalacion,nombreinstalacion,us);
            updateTablas up = new updateTablas(3);
            up.start();
        }
        if(col==6){
            String selectedSiteName = JOptionPane.showInputDialog(null,"Clave ");
            if(selectedSiteName.equalsIgnoreCase("cajamarcacajamarca")){
                try{
                    ServiceHb helper = new ServiceHb();
                    helper.iniciarTransaccion();
                    helper.eliminarObjeto(helper.obtenerObjeto(Instalacion.class, Integer.parseInt(jTable2.getValueAt(row, col).toString())));
                    helper.confirmarTransaccion();
                    helper.cerrarSesion();
                    JOptionPane.showMessageDialog(null, "Instalacion Eliminada");
                    updateTablas up = new updateTablas(3);
                    up.start();
                }
                catch(Exception io){

                }
            }
        }
        if(col==7){
            idinstalacion= Integer.parseInt(jTable2.getValueAt(row, col).toString());
            ingresoSoporte ingresoU3 = new ingresoSoporte(null, null, true,null,""+idinstalacion,1);
            updateTablas up = new updateTablas(3);
            up.start();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
