/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Bitacora.acceso;

import Login.ventas.Principal;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelmath
 */
public class observa extends javax.swing.JPanel {
    JFrame padre;
    Dimension d;
    Cuadro f;
    /**
     * Creates new form egreso
     * @param responsable
     * @param frame
     * @param direccion
     */
    public observa(String responsable, Cuadro frame, String direccion) {
        f=frame;
        d = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        setSize(1140, d.height-60-103);
        jScrollPane2.setSize(1122,  getHeight()-jScrollPane2.getY()-10);
        jPanel2.setLocation(((1140)/2) - (jPanel2.getWidth()/2), jPanel2.getY());
        jComboBox1.setLocation(((1140)/2) - (jComboBox1.getWidth()/2), jComboBox1.getY());
        jLabel4.setSize(d.width-60, 1);
        String sDirectorio = "C:\\Users\\Jan Tomislav Topic\\Owncloud\\Shared";
        File file = new File(sDirectorio);
        jComboBox1.removeAllItems();
        if (file.exists()){ // Directorio existe 
            File[] ficheros = file.listFiles();
            for (File fichero : ficheros) {
                if (fichero.getName().contains("Reporte")) {
                    jComboBox1.addItem(fichero.getName());
                }
            }
        }    
        setVisible(false);
    }

    public Dimension getD() {
        return d;
    }

    public void setD(Dimension d) {
        this.d = d;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JFrame getPadre() {
        return padre;
    }

    public void setPadre(JFrame padre) {
        this.padre = padre;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Localidad", "Documento", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(26);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 1060, 370);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-observaciones-blue.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 102, 28);

        add(jPanel2);
        jPanel2.setBounds(310, 38, 100, 28);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setOpaque(true);
        add(jLabel4);
        jLabel4.setBounds(4, 50, 1190, 1);

        jComboBox1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(260, 80, 200, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        if(col==1){
            File f = new File(jTable1.getValueAt(row, col).toString());
            if(f.exists()){
                Principal p = new Principal(jTable1.getValueAt(row, col).toString());
                p.next();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        f.setEventoMouseingreso4();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        refresh();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void refresh(){
        String sDirectorio = "C:\\Users\\Jan Tomislav Topic\\Desktop\\Cajamarca\\Dpt. SyP\\Owncloud\\Shared";
        File f = new File(sDirectorio);
        DefaultTableModel temp2 = (DefaultTableModel) jTable1.getModel();
        for(int i=temp2.getRowCount()-1;i>=0;i--){
            temp2.removeRow(i);   
        }
        if (f.exists()){ // Directorio existe 
            File[] ficheros = f.listFiles();
            for (int x=0;x<ficheros.length;x++){
                if(ficheros[x].getName().indexOf("Reporte")!=-1){
                    if(ficheros[x].getName().equalsIgnoreCase(jComboBox1.getSelectedItem().toString())){
                        String sDirectorio2 = sDirectorio+"\\"+ficheros[x].getName()+"\\Reporte turno";
                        File f2 = new File(sDirectorio2);
                        if (f2.exists()){
                            File[] ficheros2 = f2.listFiles();
                            for (int y=ficheros2.length-1;y>0;y--){
                                String cadena=ficheros2[y].getName();
                                String c1=cadena.substring(0, 4);
                                String c2=cadena.substring(4, 6);
                                String c3=cadena.substring(6, 8);
                                String c4=cadena.substring(8, 10);
                                DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
                                Object nuevo[]= {ficheros[x].getName(),sDirectorio2+"\\"+ficheros2[y].getName(),c1+"/"+c2+"/"+c3+" : Hora "+c4};
                                temp.addRow(nuevo);
                            }
                        }
                    }
                }
            }
        }else { //Directorio no existe 
            
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
