/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sgi.acceso;

import sgi.tablas.Asistente;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.DatatypeConverter;
import org.apache.poi.hssf.usermodel.HSSFCell;
import sgi.servicio.ServiceHb;
import sgi.tablas.Foto;
import sgi.tablas.Registros;
import sgi.tablas.Usuario;
import sgi.tablas.Vehiculo;

/**
 *
 * @author Angelmath
 */
public class ingresos extends javax.swing.JPanel {
    sgi.tablas.Login mnr1=null;
    String Localidad="";
    Dimension d;
    paneles f;
    public ingresos(paneles frame) {
        f=frame;
        d = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        setSize(1140, d.height-60-103);
        jPanel1.setSize(1134, d.height-60-103-100-4);
        jLabel8.setLocation(jPanel1.getWidth()-jLabel8.getWidth()-8, jPanel1.getHeight()-jLabel8.getHeight());
        jPanel2.setLocation(((1140)/2) - (jPanel2.getWidth()/2), jPanel2.getY());
        jLabel2.setSize(d.width-60, 1);
        jPanel3.setVisible(false);
        jTable1.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent Mouse_evt) {
            javax.swing.JTable table =(javax.swing.JTable) Mouse_evt.getSource();
            Point point = Mouse_evt.getPoint();
            int row = table.rowAtPoint(point);
            if (Mouse_evt.getClickCount() == 2) {
                jTextField8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()+" "+jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString()+" "+jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            }
            }
        });
        setVisible(false);
    }

    public Dimension getD() {
        return d;
    }

    public void setD(Dimension d) {
        this.d = d;
    }

    public void actual(sgi.tablas.Login mn){
        mnr1=mn;
    }
    
    public sgi.tablas.Login getMnr1() {
        return mnr1;
    }

    public void setMnr1(sgi.tablas.Login mnr1) {
        this.mnr1 = mnr1;
    }

    public String getLocalidad() {
        return Localidad;
    }

    public void setLocalidad(String Localidad) {
        this.Localidad = Localidad;
    }

    public JComboBox getjComboBox2() {
        return jComboBox2;
    }

    public void setjComboBox2(JComboBox jComboBox2) {
        this.jComboBox2 = jComboBox2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        vehiculo = new javax.swing.JLabel();
        persona = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        campo3 = new javax.swing.JLabel();
        campo1 = new javax.swing.JLabel();
        campo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        setPreferredSize(new java.awt.Dimension(880, 500));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(860, 580));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 550));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel16.setText("Cedula:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 100, 110, 30);

        jLabel10.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 180, 80, 30);

        jLabel13.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel13.setText("Apellido:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 140, 110, 30);

        jLabel14.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel14.setText("Equipos:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 220, 110, 30);

        jLabel15.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel15.setText("Acreditacion:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 300, 110, 30);

        jTextField2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextField2.setName("Nombre"); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(190, 180, 290, 30);

        jTextField4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextField4.setName("Apellido"); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(190, 140, 290, 30);

        jTextField5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextField5.setName("Cedula"); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(190, 100, 230, 30);

        jTextField6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(190, 220, 290, 30);

        jComboBox1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 300, 200, 30);

        jLabel5.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel5.setText("Placa:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 60, 97, 30);

        jTextField1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextField1.setName("Placa"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 60, 230, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/aceptar-grey.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 350, 61, 62);

        jLabel18.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel18.setText("Cantidad:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 340, 130, 30);

        jPanel3.setOpaque(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Familiar", "Habitantes", "Propietario", "Convencional", "Celular", "Status", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(24);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(250);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(1).setMinWidth(250);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(2).setMinWidth(250);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(6).setMinWidth(250);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(250);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(630, 50, 510, 320);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(680, 20, 140, 40);
        jLabel1.setVisible(false);

        jTextField8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(190, 260, 290, 30);

        jLabel19.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel19.setText("Extra:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(60, 260, 130, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(190, 340, 130, 30);

        vehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehiculo.setText("SIN IMAGEN");
        vehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        vehiculo.setOpaque(true);
        jPanel1.add(vehiculo);
        vehiculo.setBounds(500, 210, 120, 130);

        persona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persona.setText("SIN IMAGEN");
        persona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        persona.setOpaque(true);
        jPanel1.add(persona);
        persona.setBounds(500, 60, 120, 130);

        add(jPanel1);
        jPanel1.setBounds(5, 100, 1130, 420);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        campo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-reporte-grey.png"))); // NOI18N
        campo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo3MouseClicked(evt);
            }
        });
        jPanel2.add(campo3);
        campo3.setBounds(200, 0, 98, 28);

        campo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-ingreso-blue.png"))); // NOI18N
        campo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo1MouseClicked(evt);
            }
        });
        jPanel2.add(campo1);
        campo1.setBounds(0, 0, 98, 28);

        campo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-salida-grey.png"))); // NOI18N
        campo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo2MouseClicked(evt);
            }
        });
        jPanel2.add(campo2);
        campo2.setBounds(100, 0, 98, 28);

        add(jPanel2);
        jPanel2.setBounds(250, 38, 300, 28);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setOpaque(true);
        add(jLabel2);
        jLabel2.setBounds(4, 50, 1190, 1);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/caballo.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(970, 130, 215, 389);
    }// </editor-fold>//GEN-END:initComponents
    private boolean camposllenos(){
        
        return !(getjTextField2().getText().equalsIgnoreCase("")||getjTextField4().getText().equalsIgnoreCase("")||getjTextField5().getText().equalsIgnoreCase(""));
    }
    
    public void cambio(JLabel lb){
        campo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-ingreso-grey.png"))); // NOI18N
        campo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-salida-grey.png"))); // NOI18N
        campo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-reporte-grey.png"))); // NOI18N

        if(lb==campo1){
            campo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-ingreso-blue.png"))); // NOI18N
        }
        if(lb==campo2){
            campo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-salida-blue.png"))); // NOI18N
        }
        if(lb==campo3){
            campo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/mini-pestana-reporte-blue.png"))); // NOI18N
        }
    }   
    
    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        
    }//GEN-LAST:event_jLabel4KeyPressed

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }
    
    public String mostrar(String[] n){
        return "H: "+n[0]+" M: "+n[1]+" S: "+n[2];
    }
    
    public boolean yaingreso(String ci){
        try{
            ServiceHb helper = new ServiceHb();
            helper.iniciarTransaccion();
            boolean b =helper.getRegistrosexiste(ci);
            helper.cerrarSesion();
            
            return b;
        }catch(Exception io){
            JOptionPane.showMessageDialog(null, "Error en Conexion");
        }
        return false;
    }
    
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String info="";
        int configurar=0;
        if(yaingreso(jTextField5.getText())){
        if(getjLabel1().getText().equalsIgnoreCase("VEHICULO")){
            if(getjTextField1().getText().equalsIgnoreCase("")||getjTextField2().getText().equalsIgnoreCase("")||getjTextField4().getText().equalsIgnoreCase("")||getjTextField5().getText().equalsIgnoreCase("")){
                if(getjTextField1().getText().equalsIgnoreCase("")){
                    info = info + getjTextField1().getName()+ "  ";
                }
                if(getjTextField2().getText().equalsIgnoreCase("")){
                    info = info  + getjTextField2().getName()+ "  ";
                }
                if(getjTextField4().getText().equalsIgnoreCase("")){
                    info = info  + getjTextField4().getName()+ "  ";
                }
                if(getjTextField5().getText().equalsIgnoreCase("")){
                    info = info  + getjTextField5().getName();
                }
                JOptionPane.showMessageDialog(null, "Faltan campos : "+info);
            }    
        }
        else{
            if(getjTextField2().getText().equalsIgnoreCase("")||getjTextField4().getText().equalsIgnoreCase("")||getjTextField5().getText().equalsIgnoreCase("")){
                if(getjTextField2().getText().equalsIgnoreCase("")){
                    info = info  + getjTextField2().getName()+ "  ";
                }
                if(getjTextField4().getText().equalsIgnoreCase("")){
                    info = info  + getjTextField4().getName()+ "  ";
                }
                if(getjTextField5().getText().equalsIgnoreCase("")){
                    info = info  + getjTextField5().getName();
                }
                JOptionPane.showMessageDialog(null, "Faltan campos : "+info);
            }
        }
        if(info.equalsIgnoreCase("")){
                ServiceHb helper = null;
                try{
                    helper = new ServiceHb();
                    helper.iniciarTransaccion();
                    Calendar cl = Calendar.getInstance();
                    //semanal = helper.getSemanalSearch(jTextField5.getText(),cadena[cl.get(Calendar.DAY_OF_WEEK)-1]);
                    helper.cerrarSesion();
                }catch(Exception io){
                }
                if(configurar==0){
                    Usuario user = new Usuario();
                    Asistente asistente = new Asistente();
                    Registros regis = new Registros();
                    Vehiculo vehi = new Vehiculo();
                    boolean vehiculoa=true;
                    try {
                    if(!getjLabel1().getText().equalsIgnoreCase("USUARIO")){
                        helper= new ServiceHb();
                        helper.iniciarTransaccion();
                        vehi.setPlaca(getjTextField1().getText());
                        vehi.setCi(getjTextField5().getText());
                        vehiculoa=true;
                        helper.crearObjeto(vehi);
                        helper.confirmarTransaccion();
                        helper.cerrarSesion();
                    }
                    else{
                        vehiculoa=false;
                    }

                    helper= new ServiceHb();
                    helper.iniciarTransaccion();
                    user.setCi(getjTextField5().getText());
                    user.setNombre(getjTextField2().getText());
                    user.setApellido(getjTextField4().getText());
                    user.setMateriales(jTextField6.getText());
                    if(vehiculoa){
                        helper.getVehiculos();
                        user.setVehiculo(vehi);
                    }else{
                        user.setVehiculo(null);
                    }
                    helper.crearObjeto(user);
                    helper.confirmarTransaccion();
                    helper.cerrarSesion();

                    helper= new ServiceHb();
                    helper.iniciarTransaccion();
                    if(getjLabel1().getText().equalsIgnoreCase("USUARIO")){
                    regis.setTipo("P");
                    }
                    if(getjLabel1().getText().equalsIgnoreCase("VEHICULO")){
                    regis.setTipo("V");
                    }
                    regis.setLogin(getMnr1().getNombre());
                    regis.setUsuario(user);
                    regis.setLocalidad(Localidad);
                    regis.setSync("pendiente");
                    regis.setExtra(jTextField8.getText());
                    if(jComboBox1.getSelectedItem().toString().contains("Contratista")){
                        regis.setCantidad(jComboBox2.getSelectedItem().toString());
                    }else{
                        regis.setCantidad("0");
                    }
                    Date now = new Date(System.currentTimeMillis());
                    //SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    regis.setInicioTiempo(now);
                    regis.setFinTiempo(null);
                    regis.setAcreditacion(getjComboBox1().getSelectedItem().toString());
                    regis.setActualizacion(null);
                    helper.crearObjeto(regis);
                    helper.confirmarTransaccion();
                    helper.cerrarSesion();
                    //Vehiculo obj = new Vehiculo();
                } catch (Exception ex) {

                    Logger.getLogger(ingresos.class.getName()).log(Level.SEVERE, null, ex);
                }

                JOptionPane.showMessageDialog(null, "Ingreso Exitoso");            

                try {
                    helper= new ServiceHb();
                    helper.iniciarTransaccion();
                    asistente = helper.getAsistentes(getjTextField5().getText());
                    if(asistente==null){
                        asistente = new Asistente();
                        asistente.setCedula(getjTextField5().getText());
                    }else{

                    }
                    asistente.setNombre(getjTextField2().getText());
                    asistente.setApellido(getjTextField4().getText());
                    asistente.setPlaca(getjTextField1().getText());
                    asistente.setAcreditacion(getjComboBox1().getSelectedItem().toString());
                    asistente.setFamilia(jTextField8.getText());

                    helper.crearOrActualizarObjeto(asistente);
                    helper.confirmarTransaccion();
                    helper.cerrarSesion();
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                vaciar();
            }
        }
        }else{
            JOptionPane.showMessageDialog(null, "Esta CI ya se encuentra ingresada");
        }
    }//GEN-LAST:event_jLabel4MouseClicked
    
    public void vaciar(){
        getjTextField2().setText("");
        getjTextField4().setText("");
        jTextField6.setText("");
        getjTextField5().setText("");
        getjTextField1().setText("");
        jTextField8.setText("");
        persona.setIcon(null);
        vehiculo.setIcon(null);
        jComboBox2.setSelectedIndex(0);
    }
    
    public void permisibilidad(){
    
    }
    
    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        
            ServiceHb helper = new ServiceHb();
            Asistente list=null; 
            Foto foto=null; 
            try {
                helper.iniciarTransaccion();
                list = helper.getAsistentes(getjTextField5().getText());
                foto = helper.getfotoCi(getjTextField5().getText());
                helper.cerrarSesion();
            } catch (Exception ex) {
                
            }
            if(list!=null){
                getjTextField4().setText(list.getApellido());
                getjTextField2().setText(list.getNombre());
                getjComboBox1().setSelectedItem((Object)list.getAcreditacion());
                jTextField8.setText(list.getFamilia());
                if(foto!=null){
                    try{
                        String cadena= foto.getFoto();
                        byte[] decodedString = DatatypeConverter.parseBase64Binary(cadena);
                        InputStream in = new ByteArrayInputStream(decodedString);
                        BufferedImage bg = ImageIO.read(in);
                        Image im=null;
                        int xx=persona.getWidth();
                        int yy=persona.getHeight();
                        im = bg.getScaledInstance(xx,yy, 0);
                        persona.setIcon(new ImageIcon(im));
                    }catch(Exception io){
                        System.out.println(io);
                    }
                }else{
                    persona.setIcon(null);
                }
            }
        
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        
    }//GEN-LAST:event_jTextField5KeyTyped

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public void setjTextField8(JTextField jTextField8) {
        this.jTextField8 = jTextField8;
    }

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased

    }//GEN-LAST:event_jTextField5KeyReleased

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        ServiceHb helper = new ServiceHb();
        Asistente list=null; 
        Foto foto=null; 
        try {
            helper.iniciarTransaccion();
            list = helper.getAsistentes2(getjTextField1().getText());
            foto = helper.getfotoPlaca(getjTextField1().getText());
            helper.cerrarSesion();
        } catch (Exception ex) {
            
        }
        if(list!=null){
                getjTextField5().setText(list.getCedula());
                getjTextField2().setText("");
                getjTextField4().setText("");
                getjTextField8().setText("");
                if(foto!=null){
                    try{
                        String cadena= foto.getFoto();
                        byte[] imageByteArray = decodeImage(cadena);
                        InputStream in = new ByteArrayInputStream(imageByteArray);
                        BufferedImage bg = ImageIO.read(in);
                        Image im=null;
                        int xx=vehiculo.getWidth();
                        int yy=vehiculo.getHeight();
                        im = bg.getScaledInstance(xx,yy, 0);
                        vehiculo.setIcon(new ImageIcon(im));
                    }catch(Exception io){}
                }
        }

    }//GEN-LAST:event_jTextField1ActionPerformed
    public static String encodeImage(byte[] imageByteArray) {
        String v = new String( java.util.Base64.getEncoder().encode(imageByteArray), Charset.forName("UTF-8") );
        return v;
    }
    
    public static byte[] decodeImage(String imageDataString) {
        
        return java.util.Base64.getDecoder().decode(imageDataString);
    }
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/aceptar-blue.png"))); // NOI18N
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesnew/aceptar-grey.png"))); // NOI18N
    }//GEN-LAST:event_jLabel4MouseExited

    private void campo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo1MouseClicked
        //cambio(campo1);
        f.setEventoMouseingreso1();
    }//GEN-LAST:event_campo1MouseClicked

    private void campo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo2MouseClicked
        //cambio(campo2);
        f.setEventoMouseingreso2();
    }//GEN-LAST:event_campo2MouseClicked

    private void campo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo3MouseClicked
        //cambio(campo3);
        f.setEventoMouseingreso3();
    }//GEN-LAST:event_campo3MouseClicked

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
            
        
        cambiovisible(1);
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        String fileName = "C:\\cajamarca\\BASE2.xls";
        File file = new File(fileName);
        if(file.exists()){
        ExcelSheetReader n = new ExcelSheetReader();
        int base=1;
        int cant=0;
        String tipo="";
        int j=0;
        
        n.readExcelFile(fileName,0);
        List cellTempListA = (List) n.getCellDataList();
        cellTempListA.remove(0);
        
        DefaultTableModel temp4 = (DefaultTableModel) jTable1.getModel();
        for(int i=temp4.getRowCount()-1;i>=0;i--){
            temp4.removeRow(i);
        }
        for(Object x: cellTempListA){
            List cellTempListA2=(List)x;
            String mz=Integer.toString((int)((HSSFCell) cellTempListA2.get(0)).getNumericCellValue());
            String villa=Integer.toString((int)((HSSFCell) cellTempListA2.get(1)).getNumericCellValue());
            String familia=((HSSFCell) cellTempListA2.get(2)).getStringCellValue();
            String personaa=((HSSFCell) cellTempListA2.get(3)).getStringCellValue();
            String propietario=((HSSFCell) cellTempListA2.get(4)).getStringCellValue();
            String telefono="";
            try{
                if (((HSSFCell) cellTempListA2.get(6)).getCellType() == HSSFCell.CELL_TYPE_STRING) {
                    telefono =((HSSFCell) cellTempListA2.get(6)).getStringCellValue();
                }else{
                    telefono =Integer.toString((int)((HSSFCell) cellTempListA2.get(6)).getNumericCellValue());
                }
            }catch(Exception io){
                telefono="";
            }
            
            String telefonoconv="";
            try{
                if (((HSSFCell) cellTempListA2.get(5)).getCellType() == HSSFCell.CELL_TYPE_STRING) {
                    telefonoconv =((HSSFCell) cellTempListA2.get(5)).getStringCellValue();
                }else{
                    telefonoconv =Integer.toString((int)((HSSFCell) cellTempListA2.get(5)).getNumericCellValue());
                }
            }catch(Exception io){
                telefonoconv="";
            }
            
            String status=((HSSFCell) cellTempListA2.get(7)).getStringCellValue();
            
            if(personaa.contains(jTextField8.getText().toUpperCase())||propietario.contains(jTextField8.getText().toUpperCase())){
                DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
                Object nuevo1[]= {temp.getRowCount()+1,"",""};
                temp.addRow(nuevo1);
                jTable1.getModel().setValueAt(familia, cant, 0);
                jTable1.getModel().setValueAt(personaa, cant, 1);
                jTable1.getModel().setValueAt(propietario, cant, 2);
                jTable1.getModel().setValueAt(telefonoconv, cant, 3);
                jTable1.getModel().setValueAt(telefono, cant, 4);
                jTable1.getModel().setValueAt(status, cant, 5);
                jTable1.getModel().setValueAt("MZ. "+mz+ " V. "+ villa, cant, 6);
                cant++;
            }
        }
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    public JLabel getPersona() {
        return persona;
    }

    public void setPersona(JLabel persona) {
        this.persona = persona;
    }

    public JLabel getVehiculo() {
        return vehiculo;
    }

    public void setVehiculo(JLabel vehiculo) {
        this.vehiculo = vehiculo;
    }
    
    
    
    public void validar(){
        if(jComboBox1.getItemCount()>0){
            if(jComboBox1.getSelectedItem().toString().contains("Contratista")){
                jComboBox2.setVisible(true);
                jLabel18.setVisible(true);
            }else{
                jComboBox2.setVisible(false);
                jLabel18.setVisible(false);
            }
        }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        validar();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void cambiovisible(int numero){
        String fileName = "C:\\cajamarca\\BASE2.xls";
        File file = new File(fileName);
        if(file.exists()){
            if(numero==1){
                jPanel3.setVisible(true);
                jLabel2.setVisible(false);
                jLabel1.setVisible(false);
            }else{
                jPanel3.setVisible(false);
                jLabel1.setVisible(true);
                jLabel2.setVisible(true);
            }
        }
    }
    
    public String leer(String nombre) throws FileNotFoundException, IOException

    //El parametro nombre indica el nombre del archivo por ejemplo "prueba.txt" 
    {
        String strLinea;
        try{

            FileInputStream fstream = new FileInputStream(nombre);
            // Creamos el Buffer de Lectura
            try ( // Creamos el objeto de entrada
                    DataInputStream entrada = new DataInputStream(fstream)) {
                // Creamos el Buffer de Lectura
                BufferedReader buffer = new BufferedReader(new InputStreamReader(entrada));
                
                // Leer el archivo linea por linea
                while ((strLinea = buffer.readLine()) != null)   {
                    // Imprimimos la línea por pantalla
                    System.out.println (strLinea);
                }
            }

        return strLinea;

        }catch(IOException e){
            System.out.println("Error:"+e.getMessage());
        }
        return null;
    }
    
    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    
    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public void setjTextField4(JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public void setjTextField5(JTextField jTextField5) {
        this.jTextField5 = jTextField5;
    }

    public JComboBox getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campo1;
    private javax.swing.JLabel campo2;
    private javax.swing.JLabel campo3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel persona;
    private javax.swing.JLabel vehiculo;
    // End of variables declaration//GEN-END:variables
}
