/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgi.acceso;

/**
 *
 * @author Matheus
 */
public class panel_porperfil extends javax.swing.JPanel {

    /**
     * Creates new form panel_porperfil
     */
    public panel_porperfil() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 150));
        setLayout(null);

        jLabel1.setText("Foto");
        add(jLabel1);
        jLabel1.setBounds(10, 11, 101, 123);

        jLabel2.setText("Nombres:");
        add(jLabel2);
        jLabel2.setBounds(129, 11, 65, 22);

        jLabel3.setText("Apellidos:");
        add(jLabel3);
        jLabel3.setBounds(129, 44, 65, 21);

        jLabel4.setText("Aquí va nombres");
        add(jLabel4);
        jLabel4.setBounds(204, 15, 150, 14);

        jLabel5.setText("Aquí va apellidos");
        add(jLabel5);
        jLabel5.setBounds(204, 44, 150, 21);

        jLabel6.setText("Punto:");
        add(jLabel6);
        jLabel6.setBounds(129, 71, 65, 24);

        jLabel7.setText("Aquí va el punto actual");
        add(jLabel7);
        jLabel7.setBounds(204, 71, 150, 24);

        jLabel8.setText("Contacto:");
        add(jLabel8);
        jLabel8.setBounds(129, 101, 65, 24);

        jLabel9.setText("Aquí va el contacto");
        add(jLabel9);
        jLabel9.setBounds(204, 106, 119, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
