/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgi.acceso;

import javax.swing.JLabel;

/**
 *
 * @author Matheus
 */
public class panel_porperfil extends javax.swing.JPanel {

    /**
     * Creates new form panel_porperfil
     */
    public panel_porperfil() {
        initComponents();
        setVisible(true);
    }

    public JLabel getApellido() {
        return apellido;
    }

    public void setApellido(JLabel apellido) {
        this.apellido = apellido;
    }

    public JLabel getContacto() {
        return contacto;
    }

    public void setContacto(JLabel contacto) {
        this.contacto = contacto;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getNombre() {
        return nombre;
    }

    public void setNombre(JLabel nombre) {
        this.nombre = nombre;
    }

    public JLabel getPunto() {
        return punto;
    }

    public void setPunto(JLabel punto) {
        this.punto = punto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        punto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 150));
        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1);
        jLabel1.setBounds(10, 11, 101, 123);

        jLabel2.setText("Nombres:");
        add(jLabel2);
        jLabel2.setBounds(129, 11, 65, 22);

        jLabel3.setText("Apellidos:");
        add(jLabel3);
        jLabel3.setBounds(129, 44, 65, 21);

        nombre.setText("Aquí va nombres");
        add(nombre);
        nombre.setBounds(204, 15, 220, 14);

        apellido.setText("Aquí va apellidos");
        add(apellido);
        apellido.setBounds(204, 44, 220, 21);

        jLabel6.setText("Punto:");
        add(jLabel6);
        jLabel6.setBounds(129, 71, 65, 24);

        punto.setText("Aquí va el punto actual");
        add(punto);
        punto.setBounds(204, 71, 220, 24);

        jLabel8.setText("Contacto:");
        add(jLabel8);
        jLabel8.setBounds(129, 101, 65, 24);

        contacto.setText("Aquí va el contacto");
        add(contacto);
        contacto.setBounds(204, 106, 190, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel punto;
    // End of variables declaration//GEN-END:variables
}
