package rrhh.Entidad;
// Generated 23/01/2014 08:44:55 AM by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Correos  implements java.io.Serializable {


     private int id;
     private String mes;
     private String anio;
     private String envio;

    public Correos() {
    }

	
    public Correos(int id) {
        this.id = id;
    }
    public Correos(int id, String usuario, String password, String nombre) {
       this.id = id;
       this.mes = usuario;
       this.anio = password;
       this.envio = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public String getMes() {
        return mes;
    }

    public void setMes(String mes) {
        this.mes = mes;
    }

    public String getAnio() {
        return anio;
    }

    public void setAnio(String anio) {
        this.anio = anio;
    }

    public String getEnvio() {
        return envio;
    }

    public void setEnvio(String envio) {
        this.envio = envio;
    }
    



}


