package rrhh.Entidad;
// Generated 10/11/2014 15:45:54 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private int id;
     private String campo11;
     private String campo12;
     private String campo13;
     private String campo21;
     private String campo22;
     private String campo23;
     private String campo24;
     private String campo25;
     private String campo31;
     private String campo32;
     private String campo33;
     private String campo41;
     private String campo42;
     private String campo43;
     private String campo44;
     private String campo51;
     private String campo52;
     private String campo53;
     private String campo61;
     private String campo62;
     private String campo63;
     private String ci;
     private Date fecha;

    public Evaluacion() {
    }

	
    public Evaluacion(int id) {
        this.id = id;
    }
    public Evaluacion(int id, String campo11, String campo12, String campo13, String campo21, String campo22, String campo23, String campo24, String campo25, String campo31, String campo32, String campo33, String campo41, String campo42, String campo43, String campo44, String campo51, String campo52, String campo53, String campo61, String campo62, String campo63, String ci, Date fecha) {
       this.id = id;
       this.campo11 = campo11;
       this.campo12 = campo12;
       this.campo13 = campo13;
       this.campo21 = campo21;
       this.campo22 = campo22;
       this.campo23 = campo23;
       this.campo24 = campo24;
       this.campo25 = campo25;
       this.campo31 = campo31;
       this.campo32 = campo32;
       this.campo33 = campo33;
       this.campo41 = campo41;
       this.campo42 = campo42;
       this.campo43 = campo43;
       this.campo44 = campo44;
       this.campo51 = campo51;
       this.campo52 = campo52;
       this.campo53 = campo53;
       this.campo61 = campo61;
       this.campo62 = campo62;
       this.campo63 = campo63;
       this.ci = ci;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCampo11() {
        return this.campo11;
    }
    
    public void setCampo11(String campo11) {
        this.campo11 = campo11;
    }
    public String getCampo12() {
        return this.campo12;
    }
    
    public void setCampo12(String campo12) {
        this.campo12 = campo12;
    }
    public String getCampo13() {
        return this.campo13;
    }
    
    public void setCampo13(String campo13) {
        this.campo13 = campo13;
    }
    public String getCampo21() {
        return this.campo21;
    }
    
    public void setCampo21(String campo21) {
        this.campo21 = campo21;
    }
    public String getCampo22() {
        return this.campo22;
    }
    
    public void setCampo22(String campo22) {
        this.campo22 = campo22;
    }
    public String getCampo23() {
        return this.campo23;
    }
    
    public void setCampo23(String campo23) {
        this.campo23 = campo23;
    }
    public String getCampo24() {
        return this.campo24;
    }
    
    public void setCampo24(String campo24) {
        this.campo24 = campo24;
    }
    public String getCampo25() {
        return this.campo25;
    }
    
    public void setCampo25(String campo25) {
        this.campo25 = campo25;
    }
    public String getCampo31() {
        return this.campo31;
    }
    
    public void setCampo31(String campo31) {
        this.campo31 = campo31;
    }
    public String getCampo32() {
        return this.campo32;
    }
    
    public void setCampo32(String campo32) {
        this.campo32 = campo32;
    }
    public String getCampo33() {
        return this.campo33;
    }
    
    public void setCampo33(String campo33) {
        this.campo33 = campo33;
    }
    public String getCampo41() {
        return this.campo41;
    }
    
    public void setCampo41(String campo41) {
        this.campo41 = campo41;
    }
    public String getCampo42() {
        return this.campo42;
    }
    
    public void setCampo42(String campo42) {
        this.campo42 = campo42;
    }
    public String getCampo43() {
        return this.campo43;
    }
    
    public void setCampo43(String campo43) {
        this.campo43 = campo43;
    }
    public String getCampo44() {
        return this.campo44;
    }
    
    public void setCampo44(String campo44) {
        this.campo44 = campo44;
    }
    public String getCampo51() {
        return this.campo51;
    }
    
    public void setCampo51(String campo51) {
        this.campo51 = campo51;
    }
    public String getCampo52() {
        return this.campo52;
    }
    
    public void setCampo52(String campo52) {
        this.campo52 = campo52;
    }
    public String getCampo53() {
        return this.campo53;
    }
    
    public void setCampo53(String campo53) {
        this.campo53 = campo53;
    }
    public String getCampo61() {
        return this.campo61;
    }
    
    public void setCampo61(String campo61) {
        this.campo61 = campo61;
    }
    public String getCampo62() {
        return this.campo62;
    }
    
    public void setCampo62(String campo62) {
        this.campo62 = campo62;
    }
    public String getCampo63() {
        return this.campo63;
    }
    
    public void setCampo63(String campo63) {
        this.campo63 = campo63;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


