package rrhh.Entidad;
// Generated 23/01/2014 08:44:55 AM by Hibernate Tools 3.2.1.GA



/**
 * Medica generated by hbm2java
 */
public class Medica  implements java.io.Serializable {


     private int ci;
     private String hta1;
     private String hta2;
     private String cancer1;
     private String cancer2;
     private String diabetes1;
     private String diabetes2;
     private String pisquiatricas1;
     private String psiquiatricas2;
     private String coronaria1;
     private String coronaria2;
     private String acv1;
     private String acv2;
     private String asma1;
     private String asma2;
     private String otras1;
     private String otras2;
     private String gineG;
     private String gineP;
     private String gineA;
     private String gineC;
     private String ginePf;
     private String menarquia;
     private String menacmia;
     private String quirurgicos;
     private String traumaticos;
     private String alergicos;
     private String personalesOtras;
     private String personalesFum;
     private String tomaMedicamentos;
     private String alcoholismo1;
     private String alcoholismo2;
     private String alcoholismo3;
     private String alcoholismo4;
     private String deportes1;
     private String deportes2;
     private String deportes3;
     private String deportes4;
     private String drogas1;
     private String drogas2;
     private String drogas3;
     private String drogas4;
     private String tabaquismo1;
     private String tabaquismo2;
     private String tabaquismo3;
     private String tabaquismo4;
     private String riesgos;
     private String pdf;

    public Medica() {
    }

	
    public Medica(int ci) {
        this.ci = ci;
    }
    public Medica(int ci, String hta1, String hta2, String cancer1, String cancer2, String diabetes1, String diabetes2, String pisquiatricas1, String psiquiatricas2, String coronaria1, String coronaria2, String acv1, String acv2, String asma1, String asma2, String otras1, String otras2, String gineG, String gineP, String gineA, String gineC, String ginePf, String menarquia, String menacmia, String quirurgicos, String traumaticos, String alergicos, String personalesOtras, String personalesFum, String tomaMedicamentos, String alcoholismo1, String alcoholismo2, String alcoholismo3, String alcoholismo4, String deportes1, String deportes2, String deportes3, String deportes4, String drogas1, String drogas2, String drogas3, String drogas4, String tabaquismo1, String tabaquismo2, String tabaquismo3, String tabaquismo4, String riesgos, String pdf) {
       this.ci = ci;
       this.hta1 = hta1;
       this.hta2 = hta2;
       this.cancer1 = cancer1;
       this.cancer2 = cancer2;
       this.diabetes1 = diabetes1;
       this.diabetes2 = diabetes2;
       this.pisquiatricas1 = pisquiatricas1;
       this.psiquiatricas2 = psiquiatricas2;
       this.coronaria1 = coronaria1;
       this.coronaria2 = coronaria2;
       this.acv1 = acv1;
       this.acv2 = acv2;
       this.asma1 = asma1;
       this.asma2 = asma2;
       this.otras1 = otras1;
       this.otras2 = otras2;
       this.gineG = gineG;
       this.gineP = gineP;
       this.gineA = gineA;
       this.gineC = gineC;
       this.ginePf = ginePf;
       this.menarquia = menarquia;
       this.menacmia = menacmia;
       this.quirurgicos = quirurgicos;
       this.traumaticos = traumaticos;
       this.alergicos = alergicos;
       this.personalesOtras = personalesOtras;
       this.personalesFum = personalesFum;
       this.tomaMedicamentos = tomaMedicamentos;
       this.alcoholismo1 = alcoholismo1;
       this.alcoholismo2 = alcoholismo2;
       this.alcoholismo3 = alcoholismo3;
       this.alcoholismo4 = alcoholismo4;
       this.deportes1 = deportes1;
       this.deportes2 = deportes2;
       this.deportes3 = deportes3;
       this.deportes4 = deportes4;
       this.drogas1 = drogas1;
       this.drogas2 = drogas2;
       this.drogas3 = drogas3;
       this.drogas4 = drogas4;
       this.tabaquismo1 = tabaquismo1;
       this.tabaquismo2 = tabaquismo2;
       this.tabaquismo3 = tabaquismo3;
       this.tabaquismo4 = tabaquismo4;
       this.riesgos = riesgos;
       this.pdf = pdf;
    }
   
    public int getCi() {
        return this.ci;
    }
    
    public void setCi(int ci) {
        this.ci = ci;
    }
    public String getHta1() {
        return this.hta1;
    }
    
    public void setHta1(String hta1) {
        this.hta1 = hta1;
    }
    public String getHta2() {
        return this.hta2;
    }
    
    public void setHta2(String hta2) {
        this.hta2 = hta2;
    }
    public String getCancer1() {
        return this.cancer1;
    }
    
    public void setCancer1(String cancer1) {
        this.cancer1 = cancer1;
    }
    public String getCancer2() {
        return this.cancer2;
    }
    
    public void setCancer2(String cancer2) {
        this.cancer2 = cancer2;
    }
    public String getDiabetes1() {
        return this.diabetes1;
    }
    
    public void setDiabetes1(String diabetes1) {
        this.diabetes1 = diabetes1;
    }
    public String getDiabetes2() {
        return this.diabetes2;
    }
    
    public void setDiabetes2(String diabetes2) {
        this.diabetes2 = diabetes2;
    }
    public String getPisquiatricas1() {
        return this.pisquiatricas1;
    }
    
    public void setPisquiatricas1(String pisquiatricas1) {
        this.pisquiatricas1 = pisquiatricas1;
    }
    public String getPsiquiatricas2() {
        return this.psiquiatricas2;
    }
    
    public void setPsiquiatricas2(String psiquiatricas2) {
        this.psiquiatricas2 = psiquiatricas2;
    }
    public String getCoronaria1() {
        return this.coronaria1;
    }
    
    public void setCoronaria1(String coronaria1) {
        this.coronaria1 = coronaria1;
    }
    public String getCoronaria2() {
        return this.coronaria2;
    }
    
    public void setCoronaria2(String coronaria2) {
        this.coronaria2 = coronaria2;
    }
    public String getAcv1() {
        return this.acv1;
    }
    
    public void setAcv1(String acv1) {
        this.acv1 = acv1;
    }
    public String getAcv2() {
        return this.acv2;
    }
    
    public void setAcv2(String acv2) {
        this.acv2 = acv2;
    }
    public String getAsma1() {
        return this.asma1;
    }
    
    public void setAsma1(String asma1) {
        this.asma1 = asma1;
    }
    public String getAsma2() {
        return this.asma2;
    }
    
    public void setAsma2(String asma2) {
        this.asma2 = asma2;
    }
    public String getOtras1() {
        return this.otras1;
    }
    
    public void setOtras1(String otras1) {
        this.otras1 = otras1;
    }
    public String getOtras2() {
        return this.otras2;
    }
    
    public void setOtras2(String otras2) {
        this.otras2 = otras2;
    }
    public String getGineG() {
        return this.gineG;
    }
    
    public void setGineG(String gineG) {
        this.gineG = gineG;
    }
    public String getGineP() {
        return this.gineP;
    }
    
    public void setGineP(String gineP) {
        this.gineP = gineP;
    }
    public String getGineA() {
        return this.gineA;
    }
    
    public void setGineA(String gineA) {
        this.gineA = gineA;
    }
    public String getGineC() {
        return this.gineC;
    }
    
    public void setGineC(String gineC) {
        this.gineC = gineC;
    }
    public String getGinePf() {
        return this.ginePf;
    }
    
    public void setGinePf(String ginePf) {
        this.ginePf = ginePf;
    }
    public String getMenarquia() {
        return this.menarquia;
    }
    
    public void setMenarquia(String menarquia) {
        this.menarquia = menarquia;
    }
    public String getMenacmia() {
        return this.menacmia;
    }
    
    public void setMenacmia(String menacmia) {
        this.menacmia = menacmia;
    }
    public String getQuirurgicos() {
        return this.quirurgicos;
    }
    
    public void setQuirurgicos(String quirurgicos) {
        this.quirurgicos = quirurgicos;
    }
    public String getTraumaticos() {
        return this.traumaticos;
    }
    
    public void setTraumaticos(String traumaticos) {
        this.traumaticos = traumaticos;
    }
    public String getAlergicos() {
        return this.alergicos;
    }
    
    public void setAlergicos(String alergicos) {
        this.alergicos = alergicos;
    }
    public String getPersonalesOtras() {
        return this.personalesOtras;
    }
    
    public void setPersonalesOtras(String personalesOtras) {
        this.personalesOtras = personalesOtras;
    }
    public String getPersonalesFum() {
        return this.personalesFum;
    }
    
    public void setPersonalesFum(String personalesFum) {
        this.personalesFum = personalesFum;
    }
    public String getTomaMedicamentos() {
        return this.tomaMedicamentos;
    }
    
    public void setTomaMedicamentos(String tomaMedicamentos) {
        this.tomaMedicamentos = tomaMedicamentos;
    }
    public String getAlcoholismo1() {
        return this.alcoholismo1;
    }
    
    public void setAlcoholismo1(String alcoholismo1) {
        this.alcoholismo1 = alcoholismo1;
    }
    public String getAlcoholismo2() {
        return this.alcoholismo2;
    }
    
    public void setAlcoholismo2(String alcoholismo2) {
        this.alcoholismo2 = alcoholismo2;
    }
    public String getAlcoholismo3() {
        return this.alcoholismo3;
    }
    
    public void setAlcoholismo3(String alcoholismo3) {
        this.alcoholismo3 = alcoholismo3;
    }
    public String getAlcoholismo4() {
        return this.alcoholismo4;
    }
    
    public void setAlcoholismo4(String alcoholismo4) {
        this.alcoholismo4 = alcoholismo4;
    }
    public String getDeportes1() {
        return this.deportes1;
    }
    
    public void setDeportes1(String deportes1) {
        this.deportes1 = deportes1;
    }
    public String getDeportes2() {
        return this.deportes2;
    }
    
    public void setDeportes2(String deportes2) {
        this.deportes2 = deportes2;
    }
    public String getDeportes3() {
        return this.deportes3;
    }
    
    public void setDeportes3(String deportes3) {
        this.deportes3 = deportes3;
    }
    public String getDeportes4() {
        return this.deportes4;
    }
    
    public void setDeportes4(String deportes4) {
        this.deportes4 = deportes4;
    }
    public String getDrogas1() {
        return this.drogas1;
    }
    
    public void setDrogas1(String drogas1) {
        this.drogas1 = drogas1;
    }
    public String getDrogas2() {
        return this.drogas2;
    }
    
    public void setDrogas2(String drogas2) {
        this.drogas2 = drogas2;
    }
    public String getDrogas3() {
        return this.drogas3;
    }
    
    public void setDrogas3(String drogas3) {
        this.drogas3 = drogas3;
    }
    public String getDrogas4() {
        return this.drogas4;
    }
    
    public void setDrogas4(String drogas4) {
        this.drogas4 = drogas4;
    }
    public String getTabaquismo1() {
        return this.tabaquismo1;
    }
    
    public void setTabaquismo1(String tabaquismo1) {
        this.tabaquismo1 = tabaquismo1;
    }
    public String getTabaquismo2() {
        return this.tabaquismo2;
    }
    
    public void setTabaquismo2(String tabaquismo2) {
        this.tabaquismo2 = tabaquismo2;
    }
    public String getTabaquismo3() {
        return this.tabaquismo3;
    }
    
    public void setTabaquismo3(String tabaquismo3) {
        this.tabaquismo3 = tabaquismo3;
    }
    public String getTabaquismo4() {
        return this.tabaquismo4;
    }
    
    public void setTabaquismo4(String tabaquismo4) {
        this.tabaquismo4 = tabaquismo4;
    }
    public String getRiesgos() {
        return this.riesgos;
    }
    
    public void setRiesgos(String riesgos) {
        this.riesgos = riesgos;
    }
    public String getPdf() {
        return this.pdf;
    }
    
    public void setPdf(String pdf) {
        this.pdf = pdf;
    }




}


