package monitoreo.Entidad;
// Generated 12/09/2014 12:28:22 by Hibernate Tools 3.2.1.GA



/**
 * Estatico generated by hbm2java
 */
public class Estatico  implements java.io.Serializable {


     private int id;
     private String nombreVariable;
     private String condicion;
     private String valor;

    public Estatico() {
    }

	
    public Estatico(int id) {
        this.id = id;
    }
    public Estatico(int id, String nombreVariable, String condicion, String valor) {
       this.id = id;
       this.nombreVariable = nombreVariable;
       this.condicion = condicion;
       this.valor = valor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreVariable() {
        return this.nombreVariable;
    }
    
    public void setNombreVariable(String nombreVariable) {
        this.nombreVariable = nombreVariable;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


