package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int id;
     private String numero;
     private String punto;
     private String tipo;
     private String contenido;

    public Contacto() {
    }

	
    public Contacto(int id) {
        this.id = id;
    }
    public Contacto(int id, String numero, String punto, String tipo, String contenido) {
       this.id = id;
       this.numero = numero;
       this.punto = punto;
       this.tipo = tipo;
       this.contenido = contenido;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getPunto() {
        return this.punto;
    }
    
    public void setPunto(String punto) {
        this.punto = punto;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


