package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1



/**
 * Dispositivos generated by hbm2java
 */
public class Dispositivos  implements java.io.Serializable {


     private int id;
     private String mac;
     private String punto;
     private String nombre;
     private String detalle;

    public Dispositivos() {
    }

	
    public Dispositivos(int id) {
        this.id = id;
    }
    public Dispositivos(int id, String mac, String punto, String nombre, String detalle) {
       this.id = id;
       this.mac = mac;
       this.punto = punto;
       this.nombre = nombre;
       this.detalle = detalle;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }
    public String getPunto() {
        return this.punto;
    }
    
    public void setPunto(String punto) {
        this.punto = punto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


