package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1



/**
 * Foto generated by hbm2java
 */
public class Foto  implements java.io.Serializable {


     private int id;
     private String foto;
     private String nombre;
     private String observacion;
     private String usuario;
     private String vehiculo;
     private String pendiente;
     
    public Foto() {
    }

    public Foto(int id, String foto, String nombre, String observacion, String usuario, String vehiculo, String pendiente) {
        this.id = id;
        this.foto = foto;
        this.nombre = nombre;
        this.observacion = observacion;
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.pendiente = pendiente;
    }

    public Foto(int id) {
        this.id = id;
    }

    public String getPendiente() {
        return pendiente;
    }

    public void setPendiente(String pendiente) {
        this.pendiente = pendiente;
    }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(String vehiculo) {
        this.vehiculo = vehiculo;
    }




}


