package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int id;
     private String usuario;
     private String nombre;
     private String contrasenia;
     private String dispositivo;
     private String ci;
     private Integer idnivel;

    public Login() {
    }

	
    public Login(int id) {
        this.id = id;
    }
    public Login(int id, String usuario, String nombre, String contrasenia, String dispositivo, String ci, Integer idnivel) {
       this.id = id;
       this.usuario = usuario;
       this.nombre = nombre;
       this.contrasenia = contrasenia;
       this.dispositivo = dispositivo;
       this.ci = ci;
       this.idnivel = idnivel;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getDispositivo() {
        return this.dispositivo;
    }
    
    public void setDispositivo(String dispositivo) {
        this.dispositivo = dispositivo;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Integer getIdnivel() {
        return this.idnivel;
    }
    
    public void setIdnivel(Integer idnivel) {
        this.idnivel = idnivel;
    }




}


