package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Patrulla generated by hbm2java
 */
public class Patrulla  implements java.io.Serializable {


     private int id;
     private String patrulla;
     private String responsable;
     private String tiempo;
     private String guardia;
     private Date inicio;
     private Date fin;

    public Patrulla() {
    }

	
    public Patrulla(int id) {
        this.id = id;
    }
    public Patrulla(int id, String patrulla, String responsable, String tiempo, String guardia, Date inicio, Date fin) {
       this.id = id;
       this.patrulla = patrulla;
       this.responsable = responsable;
       this.tiempo = tiempo;
       this.guardia = guardia;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPatrulla() {
        return this.patrulla;
    }
    
    public void setPatrulla(String patrulla) {
        this.patrulla = patrulla;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public String getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }
    public String getGuardia() {
        return this.guardia;
    }
    
    public void setGuardia(String guardia) {
        this.guardia = guardia;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }




}


