package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1



/**
 * Premisos generated by hbm2java
 */
public class Premisos  implements java.io.Serializable {


     private int id;
     private String tipo;
     private String nivel;

    public Premisos() {
    }

	
    public Premisos(int id) {
        this.id = id;
    }
    public Premisos(int id, String tipo, String nivel) {
       this.id = id;
       this.tipo = tipo;
       this.nivel = nivel;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


