package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registros generated by hbm2java
 */
public class Registros  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private Date inicioTiempo;
     private Date finTiempo;
     private String tipo;
     private String sync;
     private String actualizacion;
     private String login;
     private String localidad;
     private String extra;
     private String cantidad;
     private String acreditacion;

    public Registros() {
    }

	
    public Registros(int id) {
        this.id = id;
    }
    public Registros(int id, Usuario usuario, Date inicioTiempo, Date finTiempo, String tipo, String sync, String actualizacion, String login, String localidad, String extra, String cantidad, String acreditacion) {
       this.id = id;
       this.usuario = usuario;
       this.inicioTiempo = inicioTiempo;
       this.finTiempo = finTiempo;
       this.tipo = tipo;
       this.sync = sync;
       this.actualizacion = actualizacion;
       this.login = login;
       this.localidad = localidad;
       this.extra = extra;
       this.cantidad = cantidad;
       this.acreditacion = acreditacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getInicioTiempo() {
        return this.inicioTiempo;
    }
    
    public void setInicioTiempo(Date inicioTiempo) {
        this.inicioTiempo = inicioTiempo;
    }
    public Date getFinTiempo() {
        return this.finTiempo;
    }
    
    public void setFinTiempo(Date finTiempo) {
        this.finTiempo = finTiempo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getSync() {
        return this.sync;
    }
    
    public void setSync(String sync) {
        this.sync = sync;
    }
    public String getActualizacion() {
        return this.actualizacion;
    }
    
    public void setActualizacion(String actualizacion) {
        this.actualizacion = actualizacion;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getExtra() {
        return this.extra;
    }
    
    public void setExtra(String extra) {
        this.extra = extra;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getAcreditacion() {
        return this.acreditacion;
    }
    
    public void setAcreditacion(String acreditacion) {
        this.acreditacion = acreditacion;
    }




}


