package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reportes generated by hbm2java
 */
public class Reportes  implements java.io.Serializable {


     private int id;
     private Integer idlogin;
     private String dispositivo;
     private Date inicio;
     private Date fin;
     private String tipo;

    public Reportes() {
    }

	
    public Reportes(int id) {
        this.id = id;
    }
    public Reportes(int id, Integer idlogin, String dispositivo, Date inicio, Date fin, String tipo) {
       this.id = id;
       this.idlogin = idlogin;
       this.dispositivo = dispositivo;
       this.inicio = inicio;
       this.fin = fin;
       this.tipo = tipo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdlogin() {
        return this.idlogin;
    }
    
    public void setIdlogin(Integer idlogin) {
        this.idlogin = idlogin;
    }
    public String getDispositivo() {
        return this.dispositivo;
    }
    
    public void setDispositivo(String dispositivo) {
        this.dispositivo = dispositivo;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


