package sgi.tablas;
// Generated 21-sep-2015 12:32:52 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Revpat generated by hbm2java
 */
public class Revpavitem  implements java.io.Serializable {


     private int id;
     private Integer idfoto;
     private String nombre;
     private Integer idrPall;
     private Date fecha;
    public Revpavitem() {
    }

    public Revpavitem(int id) {
        this.id = id;
    }

    public Revpavitem(int id, Integer idfoto, String nombre, Integer idrPall, Date fecha) {
        this.id = id;
        this.idfoto = idfoto;
        this.nombre = nombre;
        this.idrPall = idrPall;
        this.fecha = fecha;
    }
    
    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdfoto() {
        return this.idfoto;
    }
    
    public void setIdfoto(Integer idfoto) {
        this.idfoto = idfoto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getIdrPall() {
        return this.idrPall;
    }
    
    public void setIdrPall(Integer idrPall) {
        this.idrPall = idrPall;
    }




}


