package Login.Entidad;
// Generated 13/04/2015 15:59:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Caldepartamento generated by hbm2java
 */
public class Caldepartamento  implements java.io.Serializable {

     private int id;
     private String nombre;
     private String color;
     private Set calpermisosesForIdcaldepa2 = new HashSet(0);
     private Set calpermisosesForIdcaldepa1 = new HashSet(0);
     private Set calendarios = new HashSet(0);

    public Caldepartamento() {
    }

	
    public Caldepartamento(int id) {
        this.id = id;
    }
    public Caldepartamento(int id, String nombre, String color, Set calpermisosesForIdcaldepa2, Set calpermisosesForIdcaldepa1, Set calendarios) {
       this.id = id;
       this.nombre = nombre;
       this.color = color;
       this.calpermisosesForIdcaldepa2 = calpermisosesForIdcaldepa2;
       this.calpermisosesForIdcaldepa1 = calpermisosesForIdcaldepa1;
       this.calendarios = calendarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getCalpermisosesForIdcaldepa2() {
        return this.calpermisosesForIdcaldepa2;
    }
    
    public void setCalpermisosesForIdcaldepa2(Set calpermisosesForIdcaldepa2) {
        this.calpermisosesForIdcaldepa2 = calpermisosesForIdcaldepa2;
    }
    public Set getCalpermisosesForIdcaldepa1() {
        return this.calpermisosesForIdcaldepa1;
    }
    
    public void setCalpermisosesForIdcaldepa1(Set calpermisosesForIdcaldepa1) {
        this.calpermisosesForIdcaldepa1 = calpermisosesForIdcaldepa1;
    }
    public Set getCalendarios() {
        return this.calendarios;
    }
    
    public void setCalendarios(Set calendarios) {
        this.calendarios = calendarios;
    }




}


