package Login.Entidad;
// Generated 13/04/2015 15:59:07 by Hibernate Tools 3.2.1.GA
import java.util.Date;

/**
 * Calendario generated by hbm2java
 */
public class Calendario  implements java.io.Serializable {

     private int id;
     private Caldepartamento caldepartamento;
     private Login login;
     private Date fechaini;
     private Date fechafin;
     private String titulo;
     private String descripcion;
     private String hour;
     private String allhour;
     private String vinculos;
     private String visible;

    public String getHour() {
        return hour;
    }

    public void setHour(String hour) {
        this.hour = hour;
    }

    public Calendario() {
    }

     
    public Calendario(int id, Caldepartamento caldepartamento, Login login, Date fechaini, Date fechafin, String titulo, String descripcion, String hour, String allhour, String vinculos, String visible) {
        this.id = id;
        this.caldepartamento = caldepartamento;
        this.login = login;
        this.fechaini = fechaini;
        this.fechafin = fechafin;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.hour = hour;
        this.allhour = allhour;
        this.vinculos = vinculos;
        this.visible = visible;
    }

   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Caldepartamento getCaldepartamento() {
        return this.caldepartamento;
    }
    
    public void setCaldepartamento(Caldepartamento caldepartamento) {
        this.caldepartamento = caldepartamento;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public Date getFechaini() {
        return this.fechaini;
    }
    
    public void setFechaini(Date fechaini) {
        this.fechaini = fechaini;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getHora() {
        return this.hour;
    }
    
    public void setHora(String hour) {
        this.hour = hour;
    }
    public String getAllhour() {
        return this.allhour;
    }
    
    public void setAllhour(String allhour) {
        this.allhour = allhour;
    }

    public String getVinculos() {
        return vinculos;
    }

    public void setVinculos(String vinculos) {
        this.vinculos = vinculos;
    }

    public String getVisible() {
        return visible;
    }

    public void setVisible(String visible) {
        this.visible = visible;
    }




}


