package Login.Entidad;
// Generated 13/04/2015 15:59:07 by Hibernate Tools 3.2.1.GA



/**
 * Calpermisos generated by hbm2java
 */
public class Calpermisos  implements java.io.Serializable {


     private int id;
     private Caldepartamento caldepartamentoByIdcaldepa2;
     private Caldepartamento caldepartamentoByIdcaldepa1;

    public Calpermisos() {
    }

    public Calpermisos(int id, Caldepartamento caldepartamentoByIdcaldepa2, Caldepartamento caldepartamentoByIdcaldepa1) {
       this.id = id;
       this.caldepartamentoByIdcaldepa2 = caldepartamentoByIdcaldepa2;
       this.caldepartamentoByIdcaldepa1 = caldepartamentoByIdcaldepa1;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Caldepartamento getCaldepartamentoByIdcaldepa2() {
        return this.caldepartamentoByIdcaldepa2;
    }
    
    public void setCaldepartamentoByIdcaldepa2(Caldepartamento caldepartamentoByIdcaldepa2) {
        this.caldepartamentoByIdcaldepa2 = caldepartamentoByIdcaldepa2;
    }
    public Caldepartamento getCaldepartamentoByIdcaldepa1() {
        return this.caldepartamentoByIdcaldepa1;
    }
    
    public void setCaldepartamentoByIdcaldepa1(Caldepartamento caldepartamentoByIdcaldepa1) {
        this.caldepartamentoByIdcaldepa1 = caldepartamentoByIdcaldepa1;
    }




}


