package Login.Entidad;
// Generated 11/05/2014 06:20:53 PM by Hibernate Tools 3.2.1.GA

import java.sql.Date;

/**
 * Ctepagar generated by hbm2java
 */
public class Ctecobrar  implements java.io.Serializable {


     private int id;
     private Date fecha;
     private String cliente;
     private String proyecto;
     private String planpagos;
     private String observacion;
     private String factura;
     private String autfactura;
     private String montos;
     private String submontos;
     private String ivamontos;
     private String saldo;
     private String autretencion;
     private String numretencion;
     private String idretencion;
     private String totalretencion;
     private int idcliente;
     private int idproyecto;

    public Ctecobrar(int id, Date fecha, String cliente, String proyecto, String planpagos, String observacion, String factura, String autfactura, String montos, String submontos, String ivamontos, String saldo, String autretencion, String numretencion, String idretencion, String totalretencion, int idcliente, int idproyecto) {
        this.id = id;
        this.fecha = fecha;
        this.cliente = cliente;
        this.proyecto = proyecto;
        this.planpagos = planpagos;
        this.observacion = observacion;
        this.factura = factura;
        this.autfactura = autfactura;
        this.montos = montos;
        this.submontos = submontos;
        this.ivamontos = ivamontos;
        this.saldo = saldo;
        this.autretencion = autretencion;
        this.numretencion = numretencion;
        this.idretencion = idretencion;
        this.totalretencion = totalretencion;
        this.idcliente = idcliente;
        this.idproyecto = idproyecto;
    }

     
     
    public String getAutfactura() {
        return autfactura;
    }

    public void setAutfactura(String autfactura) {
        this.autfactura = autfactura;
    }

    public String getAutretencion() {
        return autretencion;
    }

    public void setAutretencion(String autretencion) {
        this.autretencion = autretencion;
    }

    public String getNumretencion() {
        return numretencion;
    }

    public void setNumretencion(String numretencion) {
        this.numretencion = numretencion;
    }

    public String getIdretencion() {
        return idretencion;
    }

    public void setIdretencion(String idretencion) {
        this.idretencion = idretencion;
    }

    public String getTotalretencion() {
        return totalretencion;
    }

    public void setTotalretencion(String totalretencion) {
        this.totalretencion = totalretencion;
    }

    public String getSubmontos() {
        return submontos;
    }

    public void setSubmontos(String submontos) {
        this.submontos = submontos;
    }

    public String getIvamontos() {
        return ivamontos;
    }

    public void setIvamontos(String ivamontos) {
        this.ivamontos = ivamontos;
    }
     
    public int getId() {
        return id;
    }

    public Ctecobrar() {
    }

    public String getFactura() {
        return factura;
    }

    public void setFactura(String factura) {
        this.factura = factura;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getSaldo() {
        return saldo;
    }

    public void setSaldo(String saldo) {
        this.saldo = saldo;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getCliente() {
        return cliente;
    }

    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

    public String getProyecto() {
        return proyecto;
    }

    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }

    public String getPlanpagos() {
        return planpagos;
    }

    public void setPlanpagos(String planpagos) {
        this.planpagos = planpagos;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public String getMontos() {
        return montos;
    }

    public void setMontos(String montos) {
        this.montos = montos;
    }

    public int getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    public int getIdproyecto() {
        return idproyecto;
    }

    public void setIdproyecto(int idproyecto) {
        this.idproyecto = idproyecto;
    }

    
  
   
    
}


