package Login.Entidad;
// Generated 28/03/2014 02:37:07 AM by Hibernate Tools 3.2.1.GA

import java.sql.Date;

/**
 * Factu generated by hbm2java
 */
public class Factura  implements java.io.Serializable {

     private int id;
     private String idnombre;
     private int idcliente;
     private int idinstalacion;
     private String idretencion;
     private String sri;
     private Date fecha;
     private Date fecha2;
     private String subtotal;
     private String subtotal0;
     private String iva;
     private String observacion;
     private String idproveedor;
     private String total;
     private String pagado;
     private String tipo;

    public int getIdcliente() {
        return idcliente;
    }

    public String getPagado() {
        return pagado;
    }

    public void setPagado(String pagado) {
        this.pagado = pagado;
    }

    public String getSubtotal0() {
        return subtotal0;
    }

    public Date getFecha2() {
        return fecha2;
    }

    public void setFecha2(Date fecha2) {
        this.fecha2 = fecha2;
    }

    public String getIdproveedor() {
        return idproveedor;
    }

    public void setIdproveedor(String idproveedor) {
        this.idproveedor = idproveedor;
    }

    public void setSubtotal0(String subtotal0) {
        this.subtotal0 = subtotal0;
    }

    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    public int getIdinstalacion() {
        return idinstalacion;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public void setIdinstalacion(int idinstalacion) {
        this.idinstalacion = idinstalacion;
    }

    public String getIdretencion() {
        return idretencion;
    }

    public void setIdretencion(String idretencion) {
        this.idretencion = idretencion;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal;
    }

    public String getIva() {
        return iva;
    }

    public void setIva(String iva) {
        this.iva = iva;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Factura(int id, int idcliente, int idinstalacion, String idretencion, String sri, Date fecha, String subtotal, String subtotal0, String iva, String observacion) {
        this.id = id;
        this.idcliente = idcliente;
        this.idinstalacion = idinstalacion;
        this.idretencion = idretencion;
        this.sri = sri;
        this.fecha = fecha;
        this.subtotal = subtotal;
        this.subtotal0 = subtotal0;
        this.iva = iva;
        this.observacion = observacion;
    }

    
     
    public Factura() {
    }
	
   

    public String getSri() {
        return sri;
    }

    public void setSri(String sri) {
        this.sri = sri;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getIdnombre() {
        return idnombre;
    }

    public void setIdnombre(String idnombre) {
        this.idnombre = idnombre;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

  
}


