package Login.Entidad;
// Generated 14/03/2014 02:47:46 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {
     private int id;
     private String ci;
     private String usuario;
     private String pass;
     private String nivel;
     private String nombre;
     private String direccion;
     private String direccionrrhh;
     private String descargas;
     private String departamento;
     private String owncloud;
     private Set loginPermisoses = new HashSet(0);
     
    public String getDireccion() {
        return direccion;
    }

    public String getDireccionrrhh() {
        return direccionrrhh;
    }

    public void setDireccionrrhh(String direccionrrhh) {
        this.direccionrrhh = direccionrrhh;
    }

    public Set getLoginPermisoses() {
        return loginPermisoses;
    }

    public void setLoginPermisoses(Set loginPermisoses) {
        this.loginPermisoses = loginPermisoses;
    }

    public String getOwncloud() {
        return owncloud;
    }

    public void setOwncloud(String owncloud) {
        this.owncloud = owncloud;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getDescargas() {
        return descargas;
    }

    public void setDescargas(String descargas) {
        this.descargas = descargas;
    }

    
    
    public Login() {
    }

	
    public Login(int id) {
        this.id = id;
    }
    public Login(int id, String ci, String usuario, String pass, String nivel, String nombre,String departamento, String owncloud) {
       this.id = id;
       this.ci = ci;
       this.departamento= departamento;
       this.usuario = usuario;
       this.pass = pass;
       this.nivel = nivel;
       this.nombre = nombre;
       this.owncloud= owncloud;
    }
   
    public int getId() {
        return this.id;
    }

    public String getDepartamento() {
        return departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }



}


