package Login.Entidad;
// Generated 13/04/2015 15:59:07 by Hibernate Tools 3.2.1.GA



/**
 * Alertas generated by hbm2java
 */
public class Owncloud  implements java.io.Serializable {


     private int id;
     private String duenio;
     private String permisos;
     private String direccion;
     private String nombre;

    public Owncloud() {
    }

    public Owncloud(int id, String duenio, String permisos, String direccion, String nombre) {
        this.id = id;
        this.duenio = duenio;
        this.permisos = permisos;
        this.direccion = direccion;
        this.nombre = nombre;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDuenio() {
        return duenio;
    }

    public void setDuenio(String duenio) {
        this.duenio = duenio;
    }

    public String getPermisos() {
        return permisos;
    }

    public void setPermisos(String permisos) {
        this.permisos = permisos;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
     
     
     
}


