package Login.Entidad;
// Generated 20/03/2014 12:36:58 PM by Hibernate Tools 3.2.1.GA



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int id;
     private String cantidad;
     private String descripcion;
     private String unitario;
     private String total;
     private String proyecto;
     private String serial;
     private String original;
    
    public String getSerial() {
        return serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    public String getOriginal() {
        return original;
    }

    public void setOriginal(String original) {
        this.original = original;
    }
     
    public Productos() {
    }

	
    public Productos(int id) {
        this.id = id;
    }
   
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUnitario() {
        return this.unitario;
    }
    
    public void setUnitario(String unitario) {
        this.unitario = unitario;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }

    public String getProyecto() {
        return proyecto;
    }

    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }




}


