package Login.Entidad;
// Generated 14/04/2014 04:44:31 AM by Hibernate Tools 3.2.1.GA



/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private int id;
     private String numero;
     private String proforma;
     private String cliente;
     private String proyecto;
     private String direccion;
     private String detalle;
     private String contacto;
     private String estado;
     private String diseno;
     
    public Ticket() {
    }

    public String getDiseno() {
        return diseno;
    }

    public void setDiseno(String diseno) {
        this.diseno = diseno;
    }

	
    public Ticket(int id) {
        this.id = id;
    }
    public Ticket(int id, String numero, String proforma, String cliente, String proyecto, String direccion, String detalle, String contacto, String estado) {
       this.id = id;
       this.numero = numero;
       this.proforma = proforma;
       this.cliente = cliente;
       this.proyecto = proyecto;
       this.direccion = direccion;
       this.detalle = detalle;
       this.contacto = contacto;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getProforma() {
        return this.proforma;
    }
    
    public void setProforma(String proforma) {
        this.proforma = proforma;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


